### ISSUE TITLE
Problems with vim-qf

### ISSUE THREAD

**Issue by amagee** [neomake/neomake#1097] opened 2017-03-08 23:36 UTC
I want Neomake to highlight errors/warnings inline in the file I'm editing but I don't want it to ever open the location window or quickfix window. How can I achieve this? I've tried fiddling with the `g:neomake_open_list` setting but without any luck.

Interestingly everything was behaving how I wanted it up until this morning when the location list window started unexpectedly showing up. Perhaps a Neovim upgrade caused this? I am using Neovim 0.2.0-DEV.

**Comment by DonnieWest** [comment] 2017-03-14 17:37
Sorry to add a "me too" to this issue, but I'm also encountering the same problems. I'm on the latest Neovim HEAD and `g:neomake_open_list` has no effect

**Comment by DonnieWest** [comment] 2017-03-14 17:58
I can confirm that downgrading Neovim fixes the issue. I'll take some time to find the exact commit that's causing the issue and report there

**Comment by blueyed** [comment] 2017-03-14 19:48
You are using `g:neomake_open_list = 0`, right?

@DonnieWest 
Thanks, that would help.

**Comment by DonnieWest** [comment] 2017-03-14 20:07
@blueyed yes. Commenting out the code that handles the location list opening still causes it to open, so I'm pretty certain that it's not this project

**Comment by blueyed** [comment] 2017-03-14 20:35
Are you using https://github.com/romainl/vim-qf?
I've noticed that it opens the list automatically in case of errors.

**Comment by blueyed** [comment] 2017-03-14 20:36
@DonnieWest 
But then I wonder why downgrading Neomake would have helped?
Maybe no errors when testing it there?

**Comment by DonnieWest** [comment] 2017-03-14 20:38
Downgrading Neovim was the fix, not Neomake. I don't think it has anything to do with Neomake

**Comment by DonnieWest** [comment] 2017-03-14 20:42
romainl/vim-qf#44 Appears to be vim-qf. No idea why downgrading Neovim would've fixed that issue, but, you can probably close this issue at this point

**Comment by blueyed** [comment] 2017-05-02 22:37
FWIW my settings:
```vim
" Causes issues with resizing (https://github.com/vim/vim/issues/931).
let g:qf_loclist_window_bottom = 0
let g:qf_window_bottom = 0

" Annoying with Neomake, but only on Vim?!
" Even with let `g:neomake_open_list = 2` !
let g:qf_auto_open_quickfix = 0
let g:qf_auto_open_loclist = 0
```

Would be nice to make it more compatible after all.. I am using an own mechanism to open the location list (only) in case of errors.

**Comment by blueyed** [comment] 2017-05-02 22:42
You can use https://github.com/blueyed/vim-qf_resize for (more advanced) automatic resizing of the qf window.

**Comment by blueyed** [comment] 2017-05-10 21:16
I thought it might be Neomake's fault here somehow, but there is not much we can do: vim-qf calls `:lwindow` when we call `:laddexpr`, and that will open the list (and not go back).

https://github.com/romainl/vim-qf/pull/48 would fix that.

Sorry for ignoring this so long: it is really annoying.

**Comment by blueyed** [comment] 2017-05-10 21:18
I've initially seen this only on Vim, but Neovim might have gotten some relevant patch (might be interesting to find out which one), but after all it's probably expected - except for that vim-qf's option is not compatible with automaking etc.  I will think about adding some workaround, depending on how the PR for vim-qf turns out.

**Comment by blueyed** [comment] 2017-05-19 18:37
https://github.com/neomake/neomake/issues/1335 will provide a workaround.

**Closed** 2017-05-19 18:42 UTC
