### ISSUE TITLE
Do not run makers on `:wq`

### ISSUE THREAD

**Issue by MaxNoe** [neomake/neomake#309] opened 2016-02-16 19:04 UTC
First: thanks for the great work!

I configured neomake to run on every write with 

```
autocmd! BufWritePost,BufEnter * Neomake
```

Works great, only downside: it also runs when leaving with `:wq` and leaves me with e.g. this after quitting a python script:

```
$ nvim test.py

Neomake: flake8 complete with exit code 0maxnoe@laptop ~
```

Which is kind of annoying.

How can I avoid, that NeoMake is also run on `:wq`?

**Comment by bartels** [comment] 2016-02-23 02:22
Adding this line fixes the problem for me

```
autocmd! QuitPre * let g:neomake_verbose = 0
```
Might it make sense for neomake to handle this automatically?

**Comment by MaxNoe** [comment] 2016-02-23 09:03
Thanks, this fixes it indeed. I think this would be a reasonable default.

**Comment by theamazingfedex** [comment] 2016-03-01 19:21
PRs are always considered, if you want to go about making this a default. Just be sure to fully document what you change and why in every pull request :)

**Comment by blueyed** [comment] 2016-05-16 01:50
@bartels 
This affects the setting when quitting any window, not Vim.
See https://github.com/neomake/neomake/issues/405#issuecomment-219322362 / https://github.com/blueyed/dotfiles/commit/4c59098cc42766f61f7f67169fdf8d90bb8437cd for a discussion and code.

**Comment by bartels** [comment] 2016-05-16 19:17
@blueyed 
Yeah, you're right.  It looks like `VimLeave` would be the event to use instead of `QuitPre`.  According to help, `VimLeave` will run only once before exiting vim.

**Comment by blueyed** [comment] 2016-12-17 23:22
Closing as dupe of #329.

**Closed by blueyed** 2016-12-17 23:22 UTC
Labels: enhancement
