### ISSUE TITLE
Passing options to makers

### ISSUE THREAD

**Issue by amitbeka** [neomake/neomake#175] opened 2015-09-11 06:21 UTC
Hi,

I'm trying to make something like this line work:

```
:Neomake pylint --rcfile=/path/to/file
```

As I work on different projects with different configurations I find it quite useful. However, I wasn't able to make this work, as I can't see any way to pass arguments to makers other than the current file path with `:%:p`, so I end up copy-pasting pylint's maker definition and calling it in other names with different rcfiles.

Is it possible? maybe we can add it to the plugin?

Thanks, Beka

P.S. this plugin was my of my main reasons to move to neovim - good work!

**Comment by aliev** [comment] 2015-09-20 22:21
@amitbeka @benekastah +1 for this feature

**Comment by ccrusius** [comment] 2015-10-02 21:06
Without this, replicating VIM's `:make` doesn't seem to be possible. The way I use `:make` is through variations of
```
:make VARIANT=debug install/lib
```
Given I have three variants and dozen of possible targets, creating individual "makers" for all possible combinations is not feasible.

**Comment by benekastah** [comment] 2015-10-07 04:49
Yeah, I agree this would be great to have. I haven't had a ton of time to add new features to this plugin recently, but I would absolutely make time for a pull request :)

Otherwise, I'll get around to it when I can.

**Comment by languitar** [comment] 2015-11-04 11:09
:+1:
It would also be nice if one could specify this options locally for a project using a vimrc (initrc) file.

**Comment by benekastah** [comment] 2015-11-05 05:26
@languitar that at least is possible (but not well documented). See #203 for an example.

**Comment by bchretien** [comment] 2015-11-05 07:53
:+1: with the exact same use case as @ccrusius (I often use `-C` to switch between build directories).

**Comment by blueyed** [comment] 2016-11-19 20:40
Closing this as duplicate of #589.

**Closed by blueyed** 2016-11-19 20:40 UTC
Labels: enhancement
