### ISSUE TITLE
cargo, rust: `cargo-check` zombie instances

### ISSUE THREAD

**Issue by dpc** [neomake/neomake#1216] opened 2017-04-19 03:46 UTC
After using neomake with recent changes to use `cargo check` for Rust/cargo projects, I've noticed that very often zombie instances are being left out. It seems it happens if vim quits before `cargo check` finishes.

Eg. `:wq` in Rust project quite reliably leaves one `cargo-check` zombie instance. (Note: I have `Neomake cargo` enabled on `BufWrite`).

What's making it even worse is that the zombie instance seem to be holding the build lock, and blocking any subsequent instances for good.

**Comment by blueyed** [comment] 2017-04-19 08:02
Are you using Vim or Neovim?
Which version?

With Vim, jobs should be stopped on exit:
```
						*job-stoponexit*
"stoponexit": {signal}	Send {signal} to the job when Vim exits.  See
			|job_stop()| for possible values.
"stoponexit": ""	Do not stop the job when Vim exits.
			The default is "term".
```

**Comment by dpc** [comment] 2017-04-19 16:20
```
> nvim --version
NVIM 0.1.7
Build type: RelWithDebInfo
Compilation: /usr/bin/cc -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -Wconversion -Wp,-U_FORTIFY_SOURCE -Wp,-D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/builddir/build/BUILD/neovim-0.1.7/obj/config -I/builddir/build/BUILD/neovim-0.1.7/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/builddir/build/BUILD/neovim-0.1.7/obj/src/nvim/auto -I/builddir/build/BUILD/neovim-0.1.7/obj/include
Compiled by mockbuild

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

**Comment by blueyed** [comment] 2017-04-19 20:31
Have not checked Neovim 0.1.7, but at least with master (soon 0.2.0) a `sleep` process gets killed.

From Neovim's `:h jobstart()` (is it there in 0.1.7 already?):
```
		  detach   : (non-pty only) Detach the job process from the
			     nvim process. The process will not get killed
			     when nvim exits. If the process dies before
			     nvim exits, on_exit will still be invoked.
```

Maybe `cargo check` ignores the (probably) TERM signal?!
Can you `kill -TERM` a `cargo check` process normally? 

Needs more investigation - I'd first check with a later Neovim, and then we could have a test that simulates it.

**Comment by fuine** [comment] 2017-04-21 10:16
I can reproduce this with the following `nvim`:
```
NVIM 0.1.7
Build type: Release
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wconversion -O2 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.1.7/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

I will try to check `cargo`'s behavior regarding `SIGTERM` handling in the following week.

**Comment by fuine** [comment] 2017-04-25 04:25
@blueyed apparently `cargo check` doesn't handle `SIGTERM` too well, see the answer on the referenced issue:

> Editors and IDEs that want to kill all of the processes that Cargo spawns should use setsid to place Cargo into its own process group, and then kill the process group (that's the typical way to do this on Unix).

I'm not sure if this can be done in `nvim`.

**Comment by dpc** [comment] 2017-04-25 05:16
So does it mean `neomake` should be starting `cargo-check` through `setsid` command?

**Comment by dpc** [comment] 2017-04-25 05:19
I'm not sure about the details of `setsid`, but maybe something like `nohup` would do as well. The point is: we don't really have to kill `cargo-check`, we just want to prevent it becoming a zombie.

**Comment by blueyed** [comment] 2017-04-28 20:31
> The point is: we don't really have to kill cargo-check, we just want to prevent it becoming a zombie.

That sounds like an issue with cargo-check then really - if I understand correctly that they are becoming zombie processes really (and not just being re-parented to `init`); that should not happen.

Has anyone tried using `setsid` or `nohup`?

The following might work for `setsid`:
```vim
let g:neomake_rust_cargo_exe = 'setsid'
let g:neomake_rust_cargo_args = ['rust'] + neomake#makers#ft#rust#cargo().args
```

**Comment by blueyed** [comment] 2017-04-28 23:06
Seems to be https://github.com/neovim/neovim/issues/6530 after all.

**Comment by blueyed** [comment] 2017-05-04 15:08
btw: https://github.com/neomake/neomake/pull/1273 would allow to prefix a job's `argv` through a hook.

**Comment by blueyed** [comment] 2017-11-13 21:57
I wonder if https://github.com/neomake/neomake/pull/1727 helps here (using `detach` with Neovim's jobstart).

**Comment by justinmk** [comment] 2018-03-18 17:38
https://github.com/neovim/neovim/issues/6530 should be fixed on Nvim HEAD.

**Comment by blueyed** [comment] 2018-03-20 19:30
Thanks, @justinmk.
According to https://github.com/neomake/neomake/issues/1704#issuecomment-374022297 using `'nvim_job_opts': {'detach': 1}` with the maker should then work around / fix this already in released Neovim versions.

**Comment by justinmk** [comment] 2018-03-20 19:39
@blueyed For unix, yes. But not for Windows.

**Comment by blueyed** [comment] 2018-03-20 19:41
Ah.
For Windows Neovim 0.2.3 is required then?
Does `'pty': 1` behave similar / could help there instead?

**Comment by justinmk** [comment] 2018-03-20 19:59
@blueyed Unlikely. It's a fundamental difference in the way Windows handles processes. See https://github.com/justinmk/neovim/commit/8d90171f8be6b92d7186ca84c42a0e07c2c71908 and https://github.com/nodejs/node/issues/3617 .

**Comment by blueyed** [comment] 2018-03-20 20:27
@justinmk 
But using detach=1 does no harm on Windows then I assume?

**Comment by justinmk** [comment] 2018-03-20 20:37
It should be fine, Nvim still manages the process.

**Closed** 2018-03-20 21:09 UTC
Labels: bug, needs info
