### ISSUE TITLE
Javac args not being set

### ISSUE THREAD

**Issue by liamaharon** [neomake/neomake#1633] opened 2017-10-02 08:56 UTC
My .java files are in `~/Github/shadow-blocks/src/project1`
My .jar files are in `~/Github/shadow-blocks/lib`

I've put this in my vimrc:
`let g:neomake_java_javac_args = ['-cp', '/home/liam/Github/shadow-blocks/lib/**:/home/liam/Github/shadow-blocks/src/project1/**']`
(I've also tried with a single and no asterisk)

When I open .java file javac shows `package <package> does not exist` for all non std library imports and `javac: cannot find symbol (E)` when classes outside of the file are referenced.

### Expected behavior

javac to not mark libraries or class files when their directory is specified in neomake_java_javac_args.

### Steps to reproduce

Described at beginning of issue.

#### Neomake debug information
Async support: 0
Current filetype: java
Windows: 0
[shell, shellcmdflag, shellslash]: ['/bin/bash', '-c', 0]

##### Enabled makers
For the current filetype ("java", used with :Neomake):
 - javac
   - append_file: 1
   - args: ['-Xlint', '-d', '/tmp/v0yP15D/22']
   - auto_enabled: 1
   - errorformat: '%E%f:%l: error: %m,%W%f:%l: warning: %m,%E%f:%l: %m,%Z%p^,%-G%.%#'
   - exe: 'javac'
NOTE: you can define g:neomake_java_enabled_makers to configure it (or b:neomake_java_enabled_makers).

For the project (used with :Neomake!): None.
NOTE: you can define g:neomake_enabled_makers to configure it.

Default maker settings:
 - remove_invalid_entries: 0
 - buffer_output: 1

##### Settings
```
g:neomake_java_ant_executable = 'ant'
g:neomake_java_checker_home = '/home/liam/.vim/plugged/neomake/autoload/neomake/makers/ft'
g:neomake_java_checkstyle_executable = 'checkstyle'
g:neomake_java_checkstyle_xml = '/usr/share/checkstyle/google_checks.xml'
g:neomake_java_gradle_executable = './gradlew'
g:neomake_java_javac_ant_classpath = {}
g:neomake_java_javac_ant_ftime = {}
g:neomake_java_javac_args = ['-cp', '/home/liam/Github/shadow-blocks/lib/**:/home/liam/Github/shadow-blocks/src/project1/**']
g:neomake_java_javac_autoload_ant_classpath = 1
g:neomake_java_javac_autoload_eclipse_classpath = 1
g:neomake_java_javac_autoload_gradle_classpath = 1
g:neomake_java_javac_autoload_maven_classpath = 1
g:neomake_java_javac_classpath = ''
g:neomake_java_javac_delete_output = 1
g:neomake_java_javac_executable = 'javac'
g:neomake_java_javac_gradle_classpath = {}
g:neomake_java_javac_gradle_ftime = {}
g:neomake_java_javac_maven_pom_classpath = {}
g:neomake_java_javac_maven_pom_ftime = {}
g:neomake_java_javac_maven_pom_properties = {}
g:neomake_java_javac_maven_pom_tags = ['build', 'properties']
g:neomake_java_javac_options = ['-Xlint']
g:neomake_java_javac_outputdir = ''
g:neomake_java_maven_executable = 'mvn'
g:neomake_java_maven_options = ''
g:neomake_place_signs = 1

  makeprg=javac
        Last set from ~/.vim/eclim/ftplugin/java.vim
```

#### :version
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:44:48)
Included patches: 1-1689
Extra patches: 8.0.0056
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
Huge version without GUI.  Features included (+) or not (-):
+acl             +cmdline_compl   +digraphs        +folding         +libcall         +mouse_dec       +netbeans_intg   +reltime         +tag_old_static  +virtualedit     -xim
+arabic          +cmdline_hist    -dnd             -footer          +linebreak       +mouse_gpm       +packages        +rightleft       -tag_any_white   +visual          -xsmp
+autocmd         +cmdline_info    -ebcdic          +fork()          +lispindent      -mouse_jsbterm   +path_extra      -ruby            -tcl             +visualextra     -xterm_clipboard
-balloon_eval    +comments        +emacs_tags      +gettext         +listcmds        +mouse_netterm   -perl            +scrollbind      +terminfo        +viminfo         -xterm_save
-browse          +conceal         +eval            -hangul_input    +localmap        +mouse_sgr       +persistent_undo +signs           +termresponse    +vreplace        -xpm
++builtin_terms  +cryptv          +ex_extra        +iconv           -lua             -mouse_sysmouse  +postscript      +smartindent     +textobjects     +wildignore
+byte_offset     +cscope          +extra_search    +insert_expand   +menu            +mouse_urxvt     +printer         +startuptime     +timers          +wildmenu
+channel         +cursorbind      +farsi           +job             +mksession       +mouse_xterm     +profile         +statusline      +title           +windows
+cindent         +cursorshape     +file_in_path    +jumplist        +modify_fname    +multi_byte      -python          -sun_workshop    -toolbar         +writebackup
-clientserver    +dialog_con      +find_in_path    +keymap          +mouse           +multi_lang      +python3         +syntax          +user_commands   -X11
-clipboard       +diff            +float           +langmap         -mouseshape      -mzscheme        +quickfix        +tag_binary      +vertsplit       -xfontset
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -Wdate-time  -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim        -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl     -L/usr/lib/python3.5/conf
ig-3.5m-x86_64-linux-gnu -lpython3.5m -lpthread -ldl -lutil -lm
```

#### :messages
```
Messages maintainer: Mike Williams <mrw@eandem.co.uk>
NERDTree: CWD is now: /home/liam/Github/shadow-blocks
"App.java" [dos] 77L, 2158C
1 change; before #1  4 seconds ago
Neomake: CancelMake: make not found: 1.
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:44:48)
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:44:48)
Neomake: Could not set clipboard: Vim(call):E354: Invalid register name: '+'.
Neomake: Could not set clipboard: Vim(call):E354: Invalid register name: '+'.
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:44:48)

**Comment by euclio** [comment] 2017-10-06 19:13
I am seeing the same issue for Perl as well.

**Comment by blueyed** [comment] 2017-10-06 21:40
It might be a mix / issue with the new config style vs. the old one.
Will have to investigate.

The output in the logfile or message when following the issue template should also provide info for where settings are coming from (missing here!).

So please try to provide this information, so I can look into it.

**Comment by euclio** [comment] 2017-10-11 13:46
Here's a copy of my info:

#### Neomake debug information
Async support: 1
Current filetype: perl
Windows: 0
[shell, shellcmdflag, shellslash]: ['/home/anrussell/.local/bin/zsh', '-c', 0]

##### Enabled makers
For the current filetype ("perl", used with :Neomake):
 - perl
   - append_file: 1
   - args: ['-c', '-X', '-Mwarnings']
   - auto_enabled: 0
   - errorformat: '%E%m at %f line %l%s,%-G%f syntax OK,%-G%f had compilation errors.'
   - exe: 'perl'
   - postprocess: function('neomake#makers#ft#perl#PerlEntryProcess')
 - verify_code
   - args: ['--vimmake', '--quiet', '--strict']
   - auto_enabled: 0
   - errorformat: '%f:%l:%m%. Severity: %t'
   - exe: 'verify_code'
   - postprocess: function('VerifyCodeEntryProcess')
NOTE: you can define g:neomake_perl_enabled_makers to configure it (or b:neomake_perl_enabled_makers).

For the project (used with :Neomake!): None.
NOTE: you can define g:neomake_enabled_makers to configure it.

Default maker settings:
 - remove_invalid_entries: 0
 - buffer_output: 1

##### Settings
```
g:neomake_error_sign = {'texthl': 'ErrorMsg', 'text': '✘'}
g:neomake_info_sign = {'texthl': 'Normal', 'text': '…'}
g:neomake_java_enabled_makers = ['checkstyle']
g:neomake_logfile = '/home/anrussell/neomake_log'
g:neomake_message_sign = {'texthl': 'Normal', 'text': '→'}
g:neomake_open_list = 2
g:neomake_perl_enabled_makers = ['perl', 'verify_code']
g:neomake_perl_perl_args = ['-c', '-X', '-Mwarnings', '-MAthena::Lib', '-MAthenaX']
g:neomake_perl_verify_code_maker = {'postprocess': function('VerifyCodeEntryProcess'), 'errorformat': '%f:%l:%m%. Severity: %t', 'args': ['--vimmake', '--quiet', '--strict'], 'exe': 'verify_code'}
g:neomake_place_signs = 1
g:neomake_rust_enabled_makers = []
g:neomake_verbose = 1
g:neomake_warning_sign = {'texthl': 'WarningMsg', 'text': '♦'}

  makeprg=perl -MAthena::Lib -MAthenaX -Wc %
        Last set from ~/.local/share/nvim/site/after/ftplugin/perl.vim
```

#### :version
```
NVIM v0.2.1-dev
Build type: Release
Compilation: /home/anrussell/.linuxbrew/Library/Homebrew/shims/linux/super/gcc-5 -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUD
E_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/tmp/neovim-20170925-18237-l7ghpv/build/config -I/tmp/neovim-20170925-18237-l7ghpv/src -I/home/anrussell/.linuxbrew/include -I/home/anrussell/.linuxbrew/include -I/home/anrussell/.linuxbrew/include -I/home/anrussell/.linuxbrew/include -I/home/anrussell/.linuxbrew/include -I
/home/anrussell/.linuxbrew/include -I/home/anrussell/.linuxbrew/include -I/tmp/neovim-20170925-18237-l7ghpv/build/src/nvim/auto -I/tmp/neovim-20170925-18237-l7ghpv/build/include
Compiled by anrussell@dev100.athenahealth.com

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/home/anrussell/.linuxbrew/Cellar/neovim/HEAD-126b2ca_1/share/nvim"
```

#### :messages
```
NVIM v0.2.1-dev
Build type: Release
Compilation: /home/anrussell/.linuxbrew/Library/Homebrew/shims/linux/super/gcc-5 -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUD
E_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/tmp/neovim-20170925-18237-l7ghpv/build/config -I/tmp/neovim-20170925-18237-l7ghpv/src -I/home/anrussell/.linuxbrew/include -I/home/anrussell/.linuxbrew/include -I/home/anrussell/.linuxbrew/include -I/home/anrussell/.linuxbrew/include -I/home/anrussell/.linuxbrew/include -I
/home/anrussell/.linuxbrew/include -I/home/anrussell/.linuxbrew/include -I/tmp/neovim-20170925-18237-l7ghpv/build/src/nvim/auto -I/tmp/neovim-20170925-18237-l7ghpv/build/include
```

**Comment by blueyed** [comment] 2017-10-11 20:46
@euclio 
You are also missing the logs.
I.e. `let g:neomake_logfile = '/tmp/neomake.log'`, then run the command, and then copy the output from the file here.

But I have noticed that `NeomakeInfo` does not display new-style settings (the dicts `g:neomake` and `b:neomake`), and that automaking is likely somehow only using the new config somewhere.

**Comment by euclio** [comment] 2017-11-08 15:08
Here's a copy of the log:

```
10:07:35 [D      ] [-.-:1:1] automake: registered events: FileType, FileChangedShellPost, InsertLeave, BufWinEnter, BufWritePost, TextChanged.
10:07:35 [D +0.55] [-.-:1:1] automake: handling event FileType.
10:07:35 [D +0.02] [-.-:1:1] Using setting automake.ignore_filetypes=['startify'] from 'global'.
10:07:35 [D      ] [-.-:1:1] Using setting errorformat='%E%m at %f line %l%s,%-G%f syntax OK,%-G%f had compilation errors.' from 'maker'.
10:07:35 [D      ] [-.-:1:1] Using setting args=['-c', '-X', '-Mwarnings'] from 'maker'.
10:07:35 [D      ] [-.-:1:1] Using setting errorformat='%f:%l:%m%. Severity: %t' from 'maker'.
10:07:35 [D      ] [-.-:1:1] Using setting args=['--vimmake', '--quiet', '--strict'] from 'maker'.
10:07:35 [D      ] [-.-:1:1] Using setting exe='verify_code' from 'maker'.
10:07:35 [D      ] [-.-:1:1] automake: configured buffer for ft=perl (perl, verify_code (default)).
10:07:35 [D      ] [-.-:1:1] automake: resetting tick because of registration changes.
10:07:35 [D      ] [-.-:1:1] automake: automake for event FileType.
10:07:35 [D      ] [-.-:1:1] Using setting automake.events={'FileType': {}, 'FileChangedShellPost': {}, 'InsertLeave': {}, 'BufWinEnter': {}, 'BufWritePost': {'delay': 0}, 'TextChanged': {}} from 'global'.
10:07:35 [D      ] [-.-:1:1] automake: tick changed (new).
10:07:35 [D      ] [-.-:1:1] automake: started timer (500ms): 0.
10:07:35 [D      ] [-.-:1:1] Using setting errorformat='%E%m at %f line %l%s,%-G%f syntax OK,%-G%f had compilation errors.' from 'maker'.
10:07:35 [D      ] [-.-:1:1] Using setting args=['-c', '-X', '-Mwarnings'] from 'maker'.
10:07:35 [D      ] [-.-:1:1] Using setting errorformat='%f:%l:%m%. Severity: %t' from 'maker'.
10:07:35 [D      ] [-.-:1:1] Using setting args=['--vimmake', '--quiet', '--strict'] from 'maker'.
10:07:35 [D      ] [-.-:1:1] Using setting exe='verify_code' from 'maker'.
10:07:35 [D      ] [-.-:1:1] automake: configured buffer for ft=perl (perl, verify_code (default)).
10:07:36 [D +0.64] [-.-:1:1] automake: handling event BufWinEnter.
10:07:36 [D      ] [-.-:1:1] Using setting automake.ignore_filetypes=['startify'] from 'global'.
10:07:36 [D      ] [-.-:1:1] automake: automake for event BufWinEnter.
10:07:36 [D      ] [-.-:1:1] Using setting automake.events={'FileType': {}, 'FileChangedShellPost': {}, 'InsertLeave': {}, 'BufWinEnter': {}, 'BufWritePost': {'delay': 0}, 'TextChanged': {}} from 'global'.
10:07:36 [D      ] [-.-:1:1] automake: tick changed (new).
10:07:36 [D      ] [-.-:1:1] automake: started timer (500ms): 1.
10:07:37 [D +0.50] [-.-:1:1] automake: callback for timer 1 (via BufWinEnter).
10:07:37 [D      ] [-.-:1:1] Using setting automake.ignore_filetypes=['startify'] from 'global'.
10:07:37 [D      ] [-.-:1:1] automake: neomake_do_automake: BufWinEnter.
10:07:37 [D      ] [-.-:1:1] automake: tick changed (new).
10:07:37 [D      ] [-.-:1:1] automake: Updating tick: 3.
10:07:37 [D      ] [-.-:1:1] automake: enabled makers: perl, verify_code.
10:07:37 [D      ] [1.-:1:1] Running makers: perl, verify_code.
10:07:37 [D      ] Defining sign: sign define neomake_file_err texthl=ErrorMsg text=✘.
10:07:37 [D      ] Defining sign: sign define neomake_project_err texthl=ErrorMsg text=✘.
10:07:37 [D      ] Defining sign: sign define neomake_file_warn texthl=WarningMsg text=♦.
10:07:37 [D      ] Defining sign: sign define neomake_project_warn texthl=WarningMsg text=♦.
10:07:37 [D      ] Defining sign: sign define neomake_file_info texthl=Normal text=….
10:07:37 [D      ] Defining sign: sign define neomake_project_info texthl=Normal text=….
10:07:37 [D      ] Defining sign: sign define neomake_file_msg texthl=Normal text=→.
10:07:37 [D      ] Defining sign: sign define neomake_project_msg texthl=Normal text=→.
10:07:37 [D      ] [-.-:1:1] Using setting append_file=1 from 'maker'.
10:07:37 [D      ] [1.1:1:1] Setting neomake_automake_tick.
10:07:37 [D      ] Skipping User autocmd NeomakeJobInit: no hooks.
10:07:37 [V      ] [1.1:1:1] Starting async job: ['perl', '-c', '-X', '-Mwarnings', '/home/anrussell/p4/anet/devmain/prod/perllib/Athena/Athena/InpatientOrder/App/Order.pm'].
10:07:37 [D      ] [1.1:1:1] cwd: /home/anrussell/p4/anet/devmain/prod.
10:07:37 [V      ] [1.1:1:1] Calling User autocmd NeomakeJobStarted with context: {'jobinfo': '…'}.
10:07:37 [D      ] Skipping User autocmd NeomakeJobInit: no hooks.
10:07:37 [V      ] [1.2:1:1] Starting async job: ['verify_code', '--vimmake', '--quiet', '--strict', '/home/anrussell/p4/anet/devmain/prod/perllib/Athena/Athena/InpatientOrder/App/Order.pm'].
10:07:37 [D      ] [1.2:1:1] cwd: /home/anrussell/p4/anet/devmain/prod.
10:07:37 [V      ] [1.2:1:1] Calling User autocmd NeomakeJobStarted with context: {'jobinfo': '…'}.
10:07:37 [D      ] [-.-:1:1] automake: started jobs: [1, 2].
10:07:37 [D      ] [1.1:1:1] stderr: perl: ['Can''t locate Athena/Object.pm in @INC (@INC contains: /usr/local/lib64/perl5/site_perl/5.16.2/x86_64-linux /usr/local/lib/perl5/perl_site/5.16.2 /usr/local/lib64/perl5/vendor_perl/5.16.2/x86_64-linux /usr/local/lib/perl5/vendor_perl/5.16.2 /usr/local/lib64/perl5/5.16.2/x86_64-linux /usr/local/lib/perl5/5.16.2 /usr/local/lib64/perl5/site_perl/5.16.2/x86_64-linux /usr/local/lib64/perl5/site_perl/5.16.2 /usr/local/lib/perl5/site_perl /usr/local/lib64/perl5/site_perl .) at /home/anrussell/p4/anet/devmain/prod/perllib/Athena/Athena/InpatientOrder/App/Order.pm line 3.', 'BEGIN failed--compilation aborted at /home/anrussell/p4/anet/devmain/prod/perllib/Athena/Athena/InpatientOrder/App/Order.pm line 3.', ''].
10:07:37 [D +0.03] [1.1:1:1] exit: perl: 2.
10:07:37 [D      ] [1.1:1:1] perl: processing 2 lines of output.
10:07:37 [D      ] [1.-:-:1] Creating location list.
10:07:37 [D      ] [-.-:1:1] Using setting postprocess=function('neomake#makers#ft#perl#PerlEntryProcess') from 'maker'.
10:07:37 [D      ] Modified list entry (postprocess): text: 'Can''t locate Athena/Object.pm in @INC (@INC contains: /usr/local/lib64/perl5/site_perl/5.16.2/x86_64-linux /usr/local/lib/perl5/perl_site/5.16.2 /usr/local/lib64/perl5/vendor_perl/5.16.2/x86_64-linux /usr/local/lib/perl5/vendor_perl/5.16.2 /usr/local/lib64/perl5/5.16.2/x86_64-linux /usr/local/lib/perl5/5.16.2 /usr/local/lib64/perl5/site_perl/5.16.2/x86_64-linux /usr/local/lib64/perl5/site_perl/5.16.2 /usr/local/lib/perl5/site_perl /usr/local/lib64/perl5/site_perl .)' => 'Can''t locate Athena/Object.pm in @INC (@INC contains: /usr/local/lib64/perl5/site_perl/5.16.2/x86_64-linux /usr/local/lib/perl5/perl_site/5.16.2 /usr/local/lib64/perl5/vendor_perl/5.16.2/x86_64-linux /usr/local/lib/perl5/vendor_perl/5.16.2 /usr/local/lib64/perl5/5.16.2/x86_64-linux /usr/local/lib/perl5/5.16.2 /usr/local/lib64/perl5/site_perl/5.16.2/x86_64-linux /usr/local/lib64/perl5/site_perl/5.16.2 /usr/local/lib/perl5/site_perl /usr/local/lib64/perl5/site_perl .) .'.
10:07:37 [D      ] Modified list entry (postprocess): text: 'BEGIN failed--compilation aborted' => 'BEGIN failed--compilation aborted .'.
10:07:37 [D      ] [1.1:1:1] Processing 2 entries.
10:07:37 [D      ] [1.-:1:1] File-level errors cleaned.
10:07:37 [D      ] [-.-:1:1] Placing sign: sign place 5000 line=3 name=neomake_file_err buffer=1.
10:07:37 [D +0.03] Skipping User autocmd NeomakeCountsChanged: no hooks.
10:07:37 [D      ] [1.1:1:1] Handling location list: executing lwindow.
10:07:37 [D +0.02] [-.-:2:2] automake: handling event BufWinEnter.
10:07:37 [D      ] [-.-:2:2] Using setting automake.ignore_filetypes=['startify'] from 'global'.
10:07:37 [D      ] [-.-:2:2] automake: configured buffer for ft= (no enabled makers).
10:07:37 [D      ] [-.-:2:2] automake: resetting tick because of registration changes.
10:07:37 [D      ] [-.-:2:2] automake: no enabled makers.
10:07:37 [D +0.11] [-.-:2:2] automake: ignoring FileType for buftype=quickfix.
10:07:37 [D +0.02] [-.-:2:2] automake: configured buffer for ft=qf (no enabled makers).
10:07:37 [D +0.02] [-.-:2:2] automake: ignoring BufWinEnter for buftype=quickfix.
10:07:37 [D +0.01] [1.1:1:1] perl: completed with exit code 2.
10:07:37 [D      ] [1.1:1:1] Cleaning jobinfo.
10:07:37 [V      ] [1.1:1:1] Calling User autocmd NeomakeJobFinished with context: {'jobinfo': '…'}.
10:07:37 [D      ] [1.-:1:1] Skipping cleaning of make info: 1 active jobs.
10:07:40 [D +3.10] [1.2:1:1] exit: verify_code: 0.
10:07:40 [D      ] [1.2:1:1] verify_code: completed with exit code 0.
10:07:40 [D      ] [1.2:1:1] Cleaning jobinfo.
10:07:40 [V      ] [1.2:1:1] Calling User autocmd NeomakeJobFinished with context: {'jobinfo': '…'}.
10:07:40 [D      ] Skipping User autocmd NeomakeFinished: no hooks.
10:07:40 [D      ] [1.-:1:1] Cleaning make info.
10:07:42 [D      ] [-.-:1:1] automake: registered events: FileType, FileChangedShellPost, InsertLeave, BufWinEnter, BufWritePost, TextChanged.
10:07:43 [D +0.49] [-.-:1:1] automake: handling event BufWinEnter.
10:07:43 [D      ] [-.-:1:1] Using setting automake.ignore_filetypes=['startify'] from 'global'.
10:07:43 [D      ] [-.-:1:1] automake: configured buffer for ft= (no enabled makers).
10:07:43 [D      ] [-.-:1:1] automake: resetting tick because of registration changes.
10:07:43 [D      ] [-.-:1:1] automake: no enabled makers.
```

**Comment by euclio** [comment] 2017-11-08 22:45
I did some more digging and it looks like some old settings were being loaded from my runtimepath. I believe it is working as expected now.

**Comment by blueyed** [comment] 2017-12-04 11:01
@liamaharon 
Are you using automaking (i.e. new-style config)?
Is `g:neomake` or `b:neomake` non-empty?
Then it is a duplicate of https://github.com/neomake/neomake/issues/1633.

**Closed** 2018-12-16 16:45 UTC
Labels: needs info
