### ISSUE TITLE
Two makers (eslint/flow) can cause error: E885: Not possible to change sign neomake_err

### ISSUE THREAD

**Issue by benjie** [neomake/neomake#787] opened 2016-11-19 11:00 UTC
Using two makers (eslint and flow) sometimes results in inability to move cursor up/down without generating errors that need to be dismissed. Workaround is to switch to using just one maker.

I think it might be because `flow` tries to add markers to more than just one file even when you just run `NeomakeFile`?

### Expected behavior

It should be possible to press `j` and `k` to move your cursor down and up without having to dismiss errors from vim on each keypress.

### Steps to reproduce

```
autocmd! BufWritePost *.js,*.jsx silent NeomakeFile
autocmd! BufWinEnter *.js,*.jsx silent NeomakeFile
```

[My vimrc](https://github.com/benjie/dotfiles/blob/master/init.vim)

I've not come up with a reliable way to reproduce it, but it seems to be triggered when you switch into a different buffer (via `C-w h` for example) when there's cross-file issues from `flow` and also local lint errors. Could be a timing issue?

In most cases writing the current file solves it (by triggering NeomakeFile?), but if not then just switching to using just one maker solves it (e.g. via `:let g:neomake_javascript_enabled_makers=['flow']`)

Here's the errors with verbose=3:

```
Neomake [156708.084]: Placing sign: sign place 5003 name=neomake_err buffer=5
Error detected while processing function neomake#CursorMoved[4]..neomake#signs#PlaceVisibleSigns[10]..neomake#signs#PlaceSign:
line   34:
E885: Not possible to change sign neomake_err
Neomake [156709.452]: Placing sign: sign place 5003 name=neomake_err buffer=5
Error detected while processing function neomake#CursorMoved[4]..neomake#signs#PlaceVisibleSigns[10]..neomake#signs#PlaceSign:
line   34:
E885: Not possible to change sign neomake_err
```

#### Neomake debug information
Async support: 1
Current filetype: javascript

##### Enabled makers
For the current filetype (with :Neomake): ['eslint', 'flow']
NOTE: you can define g:neomake_javascript_enabled_makers to configure it (or b:neomake_javascript_enabled_makers).
For the project (with :Neomake!): []
NOTE: you can define g:neomake_enabled_makers to configure it.

##### Settings
```
g:neomake_coffee_enabled_makers = ['coffeelint']
g:neomake_list_height = 5
g:neomake_javascript_enabled_makers = ['eslint', 'flow']
g:neomake_verbose = 3
g:neomake_ruby_rubocop_args = ['--format', 'emacs', '-D']
g:neomake_cjsx_enabled_makers = ['coffeelint']
g:neomake_jsx_enabled_makers = ['eslint', 'flow']
g:neomake_ruby_enabled_makers = ['rubocop']


shell: /bin/zsh
shellcmdflag: -c
Windows: 0
```

#### :version
```

NVIM 0.1.5
Build type: RelWithDebInfo
Compilation: /usr/local/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-20160826-5051-avofzl/neovim-0.1.5/build/config -I/tmp/neovim-20160826-5051-avofzl/neovim-0.1.5/src -I/tmp/neovim-20160826-5051-avofzl/neovim-0.1.5/deps-build/usr/include -I/tmp/neovim-20160826-5051-avofzl/neovim-0.1.5/deps-build/usr/include -I/tmp/neovim-20160826-5051-avofzl/neovim-0.1.5/deps-build/usr/include -I/tmp/neovim-20160826-5051-avofzl/neovim-0.1.5/deps-build/usr/include -I/tmp/neovim-20160826-5051-avofzl/neovim-0.1.5/deps-build/usr/include -I/tmp/neovim-20160826-5051-avofzl/neovim-0.1.5/deps-build/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim-20160826-5051-avofzl/neovim-0.1.5/build/src/nvim/auto -I/tmp/neovim-20160826-5051-avofzl/neovim-0.1.5/build/include
Compiled by benjiegillam@iMac.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.1.5/share/nvim"

```

#### :messages

(trimmed)

```
"src/lib/integrations.js" 86L, 2121C written
Error detected while processing function neomake#CursorMoved[4]..neomake#signs#PlaceVisibleSigns[10]..neomake#signs#PlaceSign:
line   34:
E885: Not possible to change sign neomake_err
Error detected while processing function neomake#CursorMoved[4]..neomake#signs#PlaceVisibleSigns[10]..neomake#signs#PlaceSign:
line   34:
E885: Not possible to change sign neomake_err
"src/components/ConnectIntegration.js" 93L, 2219C written
Error detected while processing function neomake#MakeHandler[44]..<SNR>126_RegisterJobOutput[25]..neomake#ProcessCurrentWindow[7]..neomake#signs#PlaceVisibleSigns[10]..neomake#signs#PlaceSign:
line   34:
E885: Not possible to change sign neomake_err
Error detected while processing function neomake#CursorMoved[4]..neomake#signs#PlaceVisibleSigns[10]..neomake#signs#PlaceSign:
line   34:
E885: Not possible to change sign neomake_err
Error detected while processing function neomake#CursorMoved[4]..neomake#signs#PlaceVisibleSigns[10]..neomake#signs#PlaceSign:
line   34:
E885: Not possible to change sign neomake_err

E121: Undefined variable: g:neomake_verbose
E488: Trailing characters
Neomake [156708.084]: Placing sign: sign place 5003 name=neomake_err buffer=5
Error detected while processing function neomake#CursorMoved[4]..neomake#signs#PlaceVisibleSigns[10]..neomake#signs#PlaceSign:
line   34:
E885: Not possible to change sign neomake_err
Neomake [156709.452]: Placing sign: sign place 5003 name=neomake_err buffer=5
Error detected while processing function neomake#CursorMoved[4]..neomake#signs#PlaceVisibleSigns[10]..neomake#signs#PlaceSign:
line   34:
E885: Not possible to change sign neomake_err
NVIM 0.1.5
Build type: RelWithDebInfo
Compilation: /usr/local/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-20160826-5051-avofzl/neovim-0.1.5/build/config -I/tmp/neovim-20160826-5051-avofzl/neovim-0.1.5/src -I/tmp/neovim-20160826-5051-avofzl/neovim-0.1.5/deps-build/usr/include -I/tmp/neovim-20160826-5051-avofzl/neovim-0.1.5/deps-build/usr/include -I/tmp/neovim-20160826-5051-avofzl/neovim-0.1.5/deps-build/usr/include -I/tmp/neovim-20160826-5051-avofzl/neovim-0.1.5/deps-build/usr/include -I/tmp/neovim-20160826-5051-avofzl/neovim-0.1.5/deps-build/usr/include -I/tmp/neovim-20160826-5051-avofzl/neovim-0.1.5/deps-build/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim-20160826-5051-avofzl/neovim-0.1.5/build/src/nvim/auto -I/tmp/neovim-20160826-5051-avofzl/neovim-0.1.5/build/include
Type  :quit<Enter>  to exit Nvim
Neomake [156974.035]: Placing sign: sign place 5003 name=neomake_err buffer=5
Error detected while processing function neomake#CursorMoved[4]..neomake#signs#PlaceVisibleSigns[10]..neomake#signs#PlaceSign:
line   34:
E885: Not possible to change sign neomake_err
Neomake [156978.369]: Placing sign: sign place 5003 name=neomake_err buffer=5
Error detected while processing function neomake#CursorMoved[4]..neomake#signs#PlaceVisibleSigns[10]..neomake#signs#PlaceSign:
line   34:
E885: Not possible to change sign neomake_err
Neomake [156980.356]: Placing sign: sign place 5003 name=neomake_err buffer=5
Error detected while processing function neomake#CursorMoved[4]..neomake#signs#PlaceVisibleSigns[10]..neomake#signs#PlaceSign:
line   34:
E885: Not possible to change sign neomake_err
```

---

See also https://github.com/neomake/neomake/issues/60#issuecomment-260666193

**Comment by verkholantsev** [comment] 2017-02-01 09:04
Same problem

**.vimrc**
```
let g:neomake_javascript_enabled_makers = ['eslint', 'flow']
```

**:messages**
```
Error detected while processing function <SNR>112_vim_exit_handler[15]..<SNR>112_exit_handler[38]..<SNR>112_RegisterJobOutput[23]..neomake#signs#PlaceVisibl
eSigns[10]..neomake#signs#PlaceSign:
line   30:
E885: Not possible to change sign neomake_err
Error detected while processing function <SNR>112_cursormoved_delayed_cb[2]..neomake#CursorMoved[5]..neomake#signs#PlaceVisibleSigns[10]..neomake#signs#Plac
eSign:
line   30:
E885: Not possible to change sign neomake_err
E885: Not possible to change sign neomake_err
E885: Not possible to change sign neomake_err
```

**Comment by jared-skinner** [comment] 2017-02-09 20:06
Same problem as well

.vimrc

```
let g:neomake_c_enabled_makers = ['gcc', 'clang']
```

:messages
```
Error detected while processing function <SNR>97_cursormoved_delayed_cb[2]..neomake#CursorMoved[5]..neomake#signs#PlaceVisibleSigns[10]..neomake#signs#PlaceSign:
line   30:
E885: Not possible to change sign neomake_err
```

**Comment by blueyed** [comment] 2017-02-09 20:25
A reproducible test case would help here.
Either as a Vader test directly, or describing it manually.

**Comment by stevenyap** [comment] 2017-03-07 06:00
I have this bug too and find it very difficult to reproduce reliably.
After thinking through about flow, I realise `flow` is actually a directory maker or project maker instead of the "normal" maker.

After I switched `flow` as a directory maker, I don't seems to have this bug anymore (cross my fingers) along with a faster and more stable/consistent performance (sometimes my flow errors doesn't show up in a project but it shows up in another).

Hence, my configuration to use `flow` (and `eslint_d`) via directory maker:
```
Plug 'neomake/neomake'
let g:neomake_flow_maker = {
        \ 'exe': 'flow',
        \ 'args': ['--from=vim', '--show-all-errors'],
        \ 'errorformat': '%EFile "%f"\, line %l\, characters %c-%m,%C%m,%Z%m',
        \ 'postprocess': function('neomake#makers#ft#javascript#FlowProcess')
        \ }
let g:neomake_eslint_d_maker = {
        \ 'exe': 'eslint_d',
        \ 'args': ['%', '-f', 'compact'],
        \ 'errorformat': '%E%f: line %l\, col %c\, Error - %m,' .
        \ '%W%f: line %l\, col %c\, Warning - %m'
        \ }

let customFTSettings = ['js']
" Run neomake for all file types except those in customFTSettings (eg. JS)
autocmd BufWritePre * if index(customFTSettings, &ft) < 0 | Neomake
" Run neomake! for JS files
autocmd! BufWritePost,BufEnter *.js Neomake! flow eslint_d
```

I find it quite ugly to have so much configuration code
but I can't seems to find out how to draw the normal makers for Neomake! usage.
Is there a way to define directory makers for neomake! so that it is a default for users?
Any guide will be good and I can submit a PR for this.

**Comment by benjie** [comment] 2017-03-07 16:13
I totally missed the entire existence of directory makers.

**Comment by stevenyap** [comment] 2017-03-08 01:35
@benjie yeah me too and I have living with the problem for quite a while.

I agree that there could be more support for directory maker such as a separate folder to contain makers for directory (currently it looks like it is only for normal makers).

Since users might be using a combination of directory makers and normal makers, I am also not sure if directory makers can be combined with normal makers such as:
```
autocmd! BufWritePost,BufEnter *.js Neomake! flow
autocmd! BufWritePost,BufEnter *.js Neomake eslint_d
```

**Comment by blueyed** [comment] 2017-03-08 01:41
@stevenyap 
That should work in general, since they use different lists for errors and counts.
But it might indeed trigger some bug.
I am heavily refactoring stuff currently, so this might get fixed on the way.  I won't investigate into this issue until then (i.e. the autolinting landed - which it depends on 2-3 other branches/PRs).

**Closed** 2017-04-24 22:25 UTC
Labels: bug
