### ISSUE TITLE
E116: Invalid arguments for function executable(maker.exe)

### ISSUE THREAD

**Issue by carlitux** [neomake/neomake#544] opened 2016-08-10 00:20 UTC
I am on an OSX this happens on scss files

**Comment by davidosomething** [comment] 2016-08-10 04:43
PR open to fix

**Comment by davidosomething** [comment] 2016-08-10 04:47
actually I'm not sure -- mine seems to work, do you have a custom sass-lint definition?

**Comment by blueyed** [comment] 2016-08-10 11:25
Closing as duplicate of #546.

**Closed by blueyed** 2016-08-10 11:25 UTC
