### ISSUE TITLE
There is no easy way to specify additional parameter (include directory) to the linter

### ISSUE THREAD

**Issue by zhou13** [neomake/neomake#603] opened 2016-09-10 00:39 UTC
In a C++ project, it is common that we need to specify the include directory using`-Iinclude`.  Currently, there is no easy way to do this unless we ignore the default maker and write our own.  Even by doing this, it is hard to achieve per-project control of the include directory.

Plugins such as YCM and deoplete-clang provides per-project configuration file such as `.ycm_extra_conf.py` and `.clang`.  It can be much more convenient if `neomake` has the similar feature.

**Comment by davidosomething** [comment] 2016-09-10 01:01
something like

```VimL
autocmd BufRead ~/projects/myproject/*
    \   let b:includes = '~/projects/myproject/includes'
    \ | let b:neomake_cpp_mylinter_args = [ '-Iinclude' . b:include_directory ]
```

might be what you're looking for. Maybe look into project specific/relative vimrc files, in conjunction.

I've actually done something similar in which I run the `phpcs` linter with special args just for WordPress projects (non-wordpress projects will use the default phpcs args):

https://github.com/davidosomething/dotfiles/blob/master/vim/plugin/plug-neomake.vim#L177-L184

**Comment by zhou13** [comment] 2016-09-10 01:06
I don't like idea to hard code any path in my vimrc.  I actually solved it using something similar using lvimrc.  However I still hope this should be natively supported.

**Comment by blueyed** [comment] 2016-09-11 14:57
Check out https://github.com/embear/vim-localvimrc, which allows for a `.lvimrc` file for your project.

But I agree that we should be able to pass in arguments to makers.
I am going to close it as duplicate of https://github.com/neomake/neomake/issues/589 for now.  There are references to other issues in there.

**Closed by blueyed** 2016-09-11 14:57 UTC
