### ISSUE TITLE
Flicker and changes to window layout on loclist update

### ISSUE THREAD

**Issue by bfredl** [neomake/neomake#1391] opened 2017-06-03 12:19 UTC
When locationlist is already opened, and `g:neomake_open_list=2` the window layout flickers or even changes on subsequent async updates to the list.

### Expected behavior

After the inital change of layout when the list opens, no further changes (or flicker) of the window layout (until the window is completely empty and closes)

### Steps to reproduce
Let `g:neomake_open_list=2`. Open some multi-window layout. Run `:Neomake` repeatedly in the same window/buffer.

**Comment by blueyed** [comment] 2017-06-03 12:54
Cannot reproduce / need more info.

I have tried the following with a minimal vimrc:
```vim
set runtimepath+=$PWD
let g:neomake_logfile = '/tmp/neomake.log'
let g:neomake_open_list = 2
```

```vim
:let maker = {'exe': 'bash', 'args': ['-c', 'echo 1:1:$RANDOM; sleep 5; echo 1:2:$RANDOM'], 'errorformat': '%E%m'}
:let maker2 = {'exe': 'bash', 'args': ['-c', 'echo 2:1:$RANDOM; sleep 3; echo 2:2:$RANDOM'], 'errorformat': '%E%m'}
:call neomake#Make(1, [maker, maker2])
```

First the results from `maker2` get added, then `maker`.
Running it several times does not change that (and previous jobs/make runs get aborted).

**Comment by bfredl** [comment] 2017-06-03 13:03
I use the clint maker as defined in https://github.com/tweekmonster/nvimdev.nvim/blob/master/autoload/nvimdev.vim
and run `:Neomake` on every BufWritePost.
The issue seems to be that `:Neomake` immediately closes the location window, instead of giving the linter some time to update it. Is this indended behavior? Perhaps there should be an option to set a timeout before closing the window.

**Comment by blueyed** [comment] 2017-06-03 14:03
Still cannot reproduce it using:
```vim
set runtimepath+=~/src/neomake
set runtimepath+=~/.vim/plugged/nvimdev.nvim/
set runtimepath+=~/.vim/plugged/vim-qf/
let g:neomake_logfile = '/tmp/neomake.log'

let g:neomake_open_list = 2

augroup my_neomake
  autocmd! BufWritePost * Neomake
augroup END
```
(tried it with and without vim-qf which might interfere here)

The log:
```
15:52:38 [D +16.1] [6.-:1] Running makers: lint.
15:52:38 [D      ] Skipping User autocmd NeomakeCountsChanged: no hooks.
15:52:38 [V      ] [6.6:1] Starting async job: ['/home/daniel/Vcs/neovim/src/clint.py', '--suppress-errors=/home/daniel/Vcs/neovim/tmp/errors/src/nvim/event/process.c.json', 'src/nvim/event/process.c'].
15:52:38 [D      ] [6.6:1] cwd: /home/daniel/Vcs/neovim.
15:52:38 [D +0.18] [6.6:1] stderr: lint: ['src/nvim/event/process.c:24:  /*-style comment found, it should be replaced with //-style.  /*-style comments are only allowed inside macros.  Note that you should not use /*-style comments to document macros itself, use doxygen-style comments for this.  [readability/old_style_comment] [5]', 'src/nvim/event/process.c:278:  /*-style comment found, it should be replaced with //-style.  /*-style comments are only allowed inside macros.  Note that you should not use /*-style comments to document macros itself, use doxygen-style comments for this.  [readability/old_style_comment] [5]', 'src/nvim/event/process.c:286:  Inner expression should be aligned as opening brace + 1 (+ 2 in case of {)  [whitespace/alignment] [2]', 'Total errors found: 3', ''].
15:52:38 [D      ] [6.6:1] exit: lint: 1.
15:52:38 [D      ] [6.6:1] lint: processing 4 lines of output.
15:52:38 [D      ] [6.6:1] Creating location list.
15:52:38 [D      ] [6.6:1] Processing 3 entries.
15:52:38 [D      ] File-level errors cleaned in buffer 1.
15:52:38 [D      ] Reusing sign: id=5000, type=neomake_warn, lnum=286.
15:52:38 [D      ] Reusing sign: id=5001, type=neomake_err, lnum=278.
15:52:38 [D      ] Reusing sign: id=5002, type=neomake_err, lnum=24.
15:52:38 [D      ] Skipping User autocmd NeomakeCountsChanged: no hooks.
15:52:38 [D      ] Handling location list: executing lwindow.
15:52:38 [D      ] [6.6:1] lint: completed with exit code 1.
15:52:38 [D      ] [6.6:1] Cleaning jobinfo.
15:52:38 [D      ] Skipping User autocmd NeomakeJobFinished: no hooks.
15:52:38 [D      ] Cleaning old signs in buffer 1: {}.
15:52:38 [D      ] Handling location list: executing lwindow.
15:52:38 [D      ] Skipping User autocmd NeomakeFinished: no hooks.
15:52:38 [D      ] [6.-:-] Cleaning make info.
```

The location list opens once and I can notice no closing/flicker when it gets refilled.

When adding `redraw | sleep 1` after the setloclist() that cleans it in https://github.com/neomake/neomake/blob/991a6faed3c388a3f41bb6ce4307915a7f7b902a/autoload/neomake.vim#L1226 I will be empty for a second.. maybe that corresponds to what you are seeing in some way though?
But emptying/creating the location list should happen just before filling it, so I speculate that some autocommand is interfering here on your side?!

**Comment by blueyed** [comment] 2017-06-03 14:22
Are you using `g:nvimdev_autorun_neomake = 1`?
Do you have Neomake multiple times in `au BufWritePost`?

**Comment by bfredl** [comment] 2017-06-03 14:29
No, once. Also it happens when invoking manually `:Neomake` so should be unrelated to autocommands. I have none that triggers on qf/loc events, no other plugins than neomake that should care about the loclist but I'll double-check later.

**Comment by blueyed** [comment] 2018-09-01 17:04
There have been changes in this regard, so I assume it might have been fixed.

Otherwise, please re-open and provide logging output for when it happens.

Also note that nvimdev has received several fixes lately.

**Closed by blueyed** 2018-09-01 17:04 UTC
Labels: needs info
