### ISSUE TITLE
Neomake glitch after every save.

### ISSUE THREAD

**Issue by drodrigo** [neomake/neomake#753] opened 2016-11-05 03:31 UTC
Hello everyone!

I've been using neomake and there's  only one thing that drives me nuts when using it. 

Everytime I save the file there's a glitch, all the icons will disappear make the screen go a little bit to the left and right away they appear again making the scren go a little bit to the right...

I'd like to know if that is the expected behavior or if there's any workaround for this problem.

Prints:

No errors or warnings
![icons_off](https://cloud.githubusercontent.com/assets/4576630/20027284/1eabc7a0-a2f7-11e6-9637-d16e82ce47c4.png)

When I have Warnings/Erros
![icons_on](https://cloud.githubusercontent.com/assets/4576630/20027287/362b2650-a2f7-11e6-9166-054e78fcfb30.png)

I don't know if there's a way to make the left border permanent so I wouldn't have this sort of problem, or something similar to this, does anyone know a fix for this?

Thanks!

**Comment by blueyed** [comment] 2016-11-05 12:36
Duplicate of #516, therefore closing.

As for me, I am using https://github.com/tomtom/quickfixsigns_vim/, which has a method to keep the sign column open all the time.

**Closed by blueyed** 2016-11-05 12:36 UTC
