### ISSUE TITLE
No enabled makers for filetype javascript.jsx

### ISSUE THREAD

**Issue by KevinSjoberg** [neomake/neomake#492] opened 2016-07-06 17:42 UTC
I'm trying to `eslint` a file with the `javascript.jsx` filetype (from plugin https://github.com/mxw/vim-jsx/tree/master/ftdetect).

I have the following in `init.vim` file:

``` vimscript
let g:neomake_verbose=3
autocmd! BufWritePost * Neomake
```

When saving my file the only output I get is the following:

```
Neomake: Nothing to make: no enabled makers
```

I'm not entirely sure why this happens as we can see that both [JavaScript](https://github.com/neomake/neomake/blob/master/autoload/neomake/makers/ft/javascript.vim#L3-L5) and [JSX](https://github.com/neomake/neomake/blob/master/autoload/neomake/makers/ft/jsx.vim#L7-L9) has default makers enabled.

I'm running `NVIM 0.1.4`.

**Comment by alexlafroscia** [comment] 2016-07-06 22:37
Seems like a duplicate of #272

**Comment by KevinSjoberg** [comment] 2016-07-07 06:57
@alexlafroscia not exactly. I don't get any makers running, not even the `JSX` ones.

**Comment by alexlafroscia** [comment] 2016-07-07 08:27
Oh, weird. Do you have a custom set of makers enabled, or just the default ones?

**Comment by KevinSjoberg** [comment] 2016-07-07 12:10
@alexlafroscia just the default ones, I've made no changes at all.

**Comment by adamyonk** [comment] 2016-07-07 16:16
FYI: https://github.com/neomake/neomake/issues/493#issuecomment-231127780

**Comment by KevinSjoberg** [comment] 2016-07-07 17:20
@adamyonk thanks for that! :+1: However, there still is a bug I presume, the ´jsx´ makersare a superset of the ´javascript´ makers and even further, ´jsx´ have ´eslint´ as a default marker. So it should run by default.

**Comment by blueyed** [comment] 2016-07-07 17:38
I'll look closer at that later / on the weekend.
JFI: you can use `12verb w` to see what functions are called and what they return.

**Comment by blueyed** [comment] 2016-09-01 22:20
@KevinSjoberg 
Did you get it working?  See https://github.com/neomake/neomake/issues/572.

**Closed** 2017-03-18 20:51 UTC
Labels: bug
