### ISSUE TITLE
Neomake not work on windows

### ISSUE THREAD

**Issue by jsfaint** [neomake/neomake#963] opened 2017-01-25 07:33 UTC
I migrate from syntastic to neomake several days ago, everything works well on Linux and macOS.
But not works on windows

### Expected behavior
After run `:Neomake` comand, the error messages should be displayed in loclist

### Steps to reproduce
OS: windows 10
vim: 8.0.0237 64bit (Downloaded from https://github.com/vim/vim-win32-installer/releases)

Run `:Neomake` command, and there are nothing showed up.
Then I enabled neomake debug information
```viml
let g:neomake_verbose = 3
```

Run `:Neomake` again, I got following message from `Neomake`
```text
Neomake [198.990]: Running makers: vint
Neomake [198.997]: [1] Starting async job: 'C:\Windows\system32\cmd.exe /c "vint --style-problem --no-color -f {file_path}:{line_number}:{column_number}:{severity}:{description} ({policy_name}) C:\Users\jia.sui\vimfiles\extra.vim"'
Neomake [199.001]: [1.7] Vim job: {'status': 'run', 'stoponexit': 'term', 'exitval': 0, 'exit_cb': 0, 'channel': channel 7 open, 'process': 5088}
Neomake [199.005]: [1.7] Vim channel: {'status': 'open', 'id': 7, 'in_io': 'pipe', 'err_mode': 'RAW', 'in_status': 'open', 'out_io': 'pipe', 'err_io': 'pipe', 'err_status': 'open', 'out_timeout': 2000, 'out_status': 'open', 'out_mode': 'RAW', 'in_mode': 'RAW', 'in_timeout': 2000, 'err_timeout': 2000}
```

I also tried python file, very simple code
```python
import sys

print(sys.api_version)

def hello():
    print('hello')
```

message as below:
![neomake-py](https://cloud.githubusercontent.com/assets/571829/22281437/f3a2b7de-e311-11e6-80ad-0a82f671b965.png)
not works too

#### Neomake debug information
Async support: 1
Current filetype: vim

##### Enabled makers
For the current filetype (with :Neomake):
 - vint
   errorformat: '%I%f:%l:%c:style_problem:%m,%f:%l:%c:%t%*[^:]:%m'
   args: ['--style-problem', '--no-color', '-f', '{file_path}:{line_number}:{column_number}:{severity}:{description} ({policy_name})']
   get_argv: function('11', {'get_argv': function('11')})
   exe: 'vint'
NOTE: you can define g:neomake_vim_enabled_makers to configure it (or b:neomake_vim_enabled_makers).

For the project (with :Neomake!): None.
NOTE: you can define g:neomake_enabled_makers to configure it.

Default maker settings:
 - remove_invalid_entries: 0
 - buffer_output: 1

##### Settings
```
g:neomake_place_signs = 1
g:neomake_verbose = 3


shell: C:\Windows\system32\cmd.exe
shellcmdflag: /c
Windows: 1
```

#### :version
```

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jan 24 2017 23:03:57)
MS-Windows 64-bit GUI version with OLE support
Included patches: 1-237
Compiled by appveyor@APPVYR-WIN
Huge version with GUI.  Features included (+) or not (-):
+acl                +cmdline_hist       -dnd                +gettext/dyn        +listcmds           +num64              +reltime            -tag_any_white      +visual
+arabic             +cmdline_info       -ebcdic             -hangul_input       +localmap           +ole                +rightleft          +tcl/dyn            +visualextra
+autocmd            +comments           +emacs_tags         +iconv/dyn          +lua/dyn            +packages           +ruby/dyn           -termguicolors      +viminfo
+balloon_eval       +conceal            +eval               +insert_expand      +menu               +path_extra         +scrollbind         -tgetent            +vreplace
+browse             +cryptv             +ex_extra           +job                +mksession          +perl/dyn           +signs              -termresponse       +wildignore
++builtin_terms     +cscope             +extra_search       +jumplist           +modify_fname       +persistent_undo    +smartindent        +textobjects        +wildmenu
+byte_offset        +cursorbind         +farsi              +keymap             +mouse              -postscript         +startuptime        +timers             +windows
+channel            +cursorshape        +file_in_path       +lambda             +mouseshape         +printer            +statusline         +title              +writebackup
+cindent            +dialog_con_gui     +find_in_path       +langmap            +multi_byte_ime/dyn +profile            -sun_workshop       +toolbar            -xfontset
+clientserver       +diff               +float              +libcall            +multi_lang         +python/dyn         +syntax             +user_commands      -xim
+clipboard          +digraphs           +folding            +linebreak          +mzscheme/dyn       +python3/dyn        +tag_binary         +vertsplit          +xpm_w32
+cmdline_compl      +directx            -footer             +lispindent         +netbeans_intg      +quickfix           +tag_old_static     +virtualedit        -xterm_save
   system vimrc file: "$VIM\vimrc"
     user vimrc file: "$HOME\_vimrc"
 2nd user vimrc file: "$HOME\vimfiles\vimrc"
 3rd user vimrc file: "$VIM\_vimrc"
      user exrc file: "$HOME\_exrc"
  2nd user exrc file: "$VIM\_exrc"
  system gvimrc file: "$VIM\gvimrc"
    user gvimrc file: "$HOME\_gvimrc"
2nd user gvimrc file: "$HOME\vimfiles\gvimrc"
3rd user gvimrc file: "$VIM\_gvimrc"
       defaults file: "$VIMRUNTIME\defaults.vim"
    system menu file: "$VIMRUNTIME\menu.vim"
Compilation: cl -c /W3 /nologo  -I. -Iproto -DHAVE_PATHDEF -DWIN32  -DFEAT_CSCOPE -DFEAT_NETBEANS_INTG -DFEAT_JOB_CHANNEL   -DFEAT_XPM_W32   -DWINVER=0x500 -D_WIN32_WINNT=0x500  /Fo.\ObjGXOULYHTRZAMD64/ /MP -DHAVE_STDINT_H /Ox /GL -DNDEBUG  /Zl /MT -DFEAT_OLE -DFEAT_MBYTE_IME -DDYNAMIC_IME -DFEAT_MBYTE -DFEAT_GUI_W32 -DFEAT_DIRECTX -DDYNAMIC_DIRECTX -DDYNAMIC_ICONV -DDYNAMIC_GETTEXT -DFEAT_TCL -DDYNAMIC_TCL -DDYNAMIC_TCL_DLL=\"tcl86.dll\" -DDYNAMIC_TCL_VER=\"8.6\" -DFEAT_LUA -DDYNAMIC_LUA -DDYNAMIC_LUA_DLL=\"lua53.dll\" -DFEAT_PYTHON -DDYNAMIC_PYTHON -DDYNAMIC_PYTHON_DLL=\"python27.dll\" -DFEAT_PYTHON3 -DDYNAMIC_PYTHON3 -DDYNAMIC_PYTHON3_DLL=\"python35.dll\" -DFEAT_MZSCHEME -I "C:\Program Files\Racket\include" -DMZ_PRECISE_GC -DDYNAMIC_MZSCHEME -DDYNAMIC_MZSCH_DLL=\"libracket3m_a0solc.dll\" -DDYNAMIC_MZGC_DLL=\"libracket3m_a0solc.dll\" -DFEAT_PERL -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DDYNAMIC_PERL -DDYNAMIC_PERL_DLL=\"perl524.dll\" -DFEAT_RUBY -DDYNAMIC_RUBY -DDYNAMIC_RUBY_VER=22 -DDYNAMIC_RUBY_DLL=\"x64-msvcrt-ruby220.dll\" -DFEAT_HUGE /Fd.\ObjGXOULYHTRZAMD64/ /Zi
Linking: link /RELEASE /nologo /subsystem:windows /LTCG:STATUS oldnames.lib kernel32.lib advapi32.lib shell32.lib gdi32.lib  comdlg32.lib ole32.lib uuid.lib /machine:AMD64 gdi32.lib version.lib   winspool.lib comctl32.lib advapi32.lib shell32.lib  /machine:AMD64 /nodefaultlib libcmt.lib oleaut32.lib user32.lib  /nodefaultlib:lua53.lib  /STACK:8388608  /nodefaultlib:python27.lib /nodefaultlib:python35.lib   "C:\Tcl\lib\tclstub86.lib" WSock32.lib xpm\x64\lib\libXpm.lib /PDB:gvim.pdb -debug
```

#### :messages
```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
"~\vimfiles\extra.vim" [unix] 17L, 458C
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jan 24 2017 23:03:57)
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jan 24 2017 23:03:57)
```

**Comment by blueyed** [comment] 2017-01-25 10:58
Is it only about the python maker?
Looks like there is a SyntaxError in it, maybe because of line endings?
I could imagine they need to be different on Windows maybe?!

**Comment by jsfaint** [comment] 2017-01-25 12:34
Hi @blueyed thanks for your reply.
It's not only about the python maker.

I use vim-vint for VimL
On linux and macOS, neomake works with vim-vint, but on windows neomake not works
This message was displayed in loclist
```
|| vint ERROR: no such file or directory: `({policy_name})`
```
If I run vint directly, it will show the right result

I tried some other maker, some maker can be invoked by `Neomake <maker>`, but can't be invoked by `Neomake` on windows
Like `standard` for javascript, it works with `Neomake standard`, but if I only input `Neomake`, nothing happened

**Comment by blueyed** [comment] 2017-01-25 12:44
Yes, apparently the quoting on Windows is wrong.
Seems to be a duplicate of https://github.com/neomake/neomake/issues/959, right?

**Comment by blueyed** [comment] 2017-01-25 12:55
See https://github.com/neomake/neomake/issues/959#issuecomment-275101057.

**Comment by jsfaint** [comment] 2017-01-25 12:56
Yes, it's duplicate with #959 but for different maker.
Thanks you!

**Closed** 2017-01-25 13:11 UTC
