### ISSUE TITLE
neomake#util#ExpandArgs requires the metacharacters to be at the start of the string

### ISSUE THREAD

**Issue by jamessan** [neomake/neomake#990] opened 2017-02-03 04:25 UTC
I'm unable to define an `args` that has the cmdline-special metacharacters at an arbitrary position in the string.  Specifically, I was trying to use

```vim
let g:neomake_c_lint_maker = {
    \ 'exe': 'make',
    \ 'args': ['clint', 'LINT_FILE=%'],
    \ 'append_file': 0,
    \ 'errorformat': '%f:%l: %m',
    \}
```

to perform linting when working on Neovim.

### Expected behavior

I was hoping for `:Neomake` to successfully lint the current file.  However, `:Neomake` ends up running the command `make clint LINT_FILE=%` instead of `make clint LINT_FILE=src/nvim/message.c`.

**Comment by blueyed** [comment] 2017-02-03 10:59
You could use `expand('%')`.
I don't remember the details, but it was made less magical on purpose.

**Comment by jamessan** [comment] 2017-02-03 14:42
> I don't remember the details, but it was made less magical on purpose.

Ok.  I'm fine with that, but it should be clarified in the documentation what the restrictions are and that a function should be used for more control.

**Comment by blueyed** [comment] 2017-02-03 19:02
Agreed.
I have to investigate why it was changed after all.
IIRC it was causing problems when you wanted to use a `%` by itself, and the escaping was not really consistent etc.

**Comment by jamessan** [comment] 2017-02-03 19:08
Yeah, that was changed here: https://github.com/neomake/neomake/pull/845

**Comment by tweekmonster** [comment] 2017-02-03 21:20
> You could use expand('%').

In the argument list as a string `['expand(''%'')']` or on the spot with `[expand('%')]`?  I'd think that the latter would just make it use the current buffer and always use it from then on.

Also, if `'args'` is a string, `%` will be expanded right?

> Yeah, that was changed here: #845

Hmm, so the problem is with `%s` and I guess Windows path separators like `C:\\%`?  I'd still like it to expand like in #991.  I can adjust it so that `%s` and `\\%` work correctly.  But, I won't be mad if you disagree and want to close it.

**Comment by blueyed** [comment] 2017-02-03 22:01
> on the spot with `[expand('%')]`

The function is called every time the maker is used, and IIRC in the context of the buffer (where you call it).  There is no caching involved here.

`args': ['clint', 'LINT_FILE='.expand('%')],` should work therefore probably.

> Also, if 'args' is a string, % will be expanded right?

No, if you use a string, it will be used as-is, no escaping happens.

> I'd still like it to expand like in #991. I can adjust it so that %s and \\% work correctly. 

OK.

There is some special escaping for `neomake#utils#MakerFromCommand` in https://github.com/neomake/neomake/blob/bbef95f6799b1f69fbea224d102d39ba4e2cfbd3/autoload/neomake/utils.vim#L192-L193, which should use the new method then probably?!

**Comment by tweekmonster** [comment] 2017-02-03 22:31
> 'args': ['clint', 'LINT_FILE='.expand('%')], should work therefore probably.

This doesn't make sense to me.  It would expand as soon as it's assigned to `g:neomake_c_lint_maker`, right?  Is there some other sorcery at work here?

> neomake#utils#MakerFromCommand

Do you mean have `neomake#utils#MakerFromCommand` call `neomake#utils#ExpandArgs()`?  If so, yeah that would make sense for consistency and maintenance.

**Comment by blueyed** [comment] 2017-02-03 22:36
Oh, sorry.. I was thinking about the default makers and there function/return value.. for `g:neomake_c_lint_maker` you would need a function for `args`, yes.

> Do you mean have neomake#utils#MakerFromCommand call neomake#utils#ExpandArgs()? 

Yes.

**Closed** 2017-02-10 23:51 UTC
Labels: bug
