### ISSUE TITLE
No output from `:Neomake!` (with makeprg)

### ISSUE THREAD

**Issue by JustAPerson** [neomake/neomake#294] opened 2016-01-31 07:50 UTC
Hi,

leaving `makeprg` and `errorformat` unchanged from the neovim defaults should cause `:Neomake!` to run any makefile in the working directory. However, no output is emitted.

Consider this makefile

``` make
run:
    echo test
```

When running `:make` the following is emitted to the quickfix window:

```
echo test
test
```

But nothing is emitted to the quickfix window after running `:Neomake!`

**Comment by blueyed** [comment] 2016-06-06 22:16
Confirmed.
When adding `false` though to the target, the following appears:

> Makefile|5| recipe for target 'run' failed

Did this work for you before?

**Comment by blueyed** [comment] 2017-06-18 00:12
Seems to be fixed by now.

I get the expected output after `:Neomake!` and `:copen`.

**Closed by blueyed** 2017-06-18 00:12 UTC
Labels: question
