### ISSUE TITLE
E885: Not possible to change sign neomake_err

### ISSUE THREAD

**Issue by ivegotasthma** [neomake/neomake#1099] opened 2017-03-09 18:11 UTC
```
Error detected while processing function <SNR>48_exit_handler[38]..<SNR>48_RegisterJobOutput[19]..<SNR>48_ProcessJobOutput[29]..<SNR>48_AddExprCallback[97]..
neomake#signs#PlaceSign:
line   30:
E885: Not possible to change sign neomake_err
Error detected while processing function <SNR>48_exit_handler[38]..<SNR>48_RegisterJobOutput:
line   19:
E171: Missing :endif
Error detected while processing function <SNR>48_exit_handler:
line   38:
```
E171: Missing :endif

### Expected behavior

it not to crash

### Steps to reproduce

I was editing a `.cpp` file

I'm running neovim with the latest neomake

**Comment by blueyed** [comment] 2017-03-09 18:36
Can you reproduce it, or did it happen just once?
If so, please provide the debug output via `neomake_logfile`.

**Comment by ivegotasthma** [comment] 2017-03-09 18:38
It happened multiple times after a couple of saves while working on the file. I can't get the logs right now, I'll have to check tomorrow

**Comment by ivegotasthma** [comment] 2017-03-10 17:51
Forgot the logs, but I fixed the problem by passing the `neomake_cpp_gcc_maker` a flag, `-std=c++11`, that seems to have fixed it

**Comment by nukr** [comment] 2017-03-12 11:44
I am encounter same issue in golang here.

I can reproduce by switch these two file.

Error message same as @ivegotasthma 

```go
package squashspace

func squashspace(b []byte) []byte {
}
```

```go
package squashspace

import "testing"

func TestSquashSpace(t *testing.T) {
	actual := "hi,  there"
	expected := "hi, there"
	actual = squashspace(actual)
	if actual != expected {
		t.Errorf("%s, expected %s\n", actual, expected)
	}
}
```

## my neomake config

```vim
autocmd! BufWritePost,BufEnter * Neomake
let g:neomake_verbose = 0
let g:neomake_logfile = "/Users/nukr/.neomake_logfile"
let g:neomake_go_gobuild_maker = {
    \ 'exe': 'sh',
    \ 'args': ['-c', 'go build -o ' . neomake#utils#DevNull() . ' ./\$0', '%:h'],
    \ 'errorformat':
        \ '%W%f:%l: warning: %m,' .
        \ '%E%f:%l:%c:%m,' .
        \ '%E%f:%l:%m,' .
        \ '%C%\s%\+%m,' .
        \ '%-G#%.%#'
    \ }
```

## my neomake_logfile
```
19:41:18 [D      ] [1] Nothing to make: no enabled file mode makers.
19:41:19 [D +1.30] [2] Nothing to make: no enabled file mode makers.
19:41:19 [D +0.02] [3] Nothing to make: no enabled file mode makers.
19:41:23 [D +4.18] [4] Nothing to make: no enabled file mode makers.
19:41:23 [D +0.04] [5] Running makers: go (auto), golint (auto), govet (auto)
19:41:23 [V      ] [5] Starting async job: ['go', 'test', '-c', '-o', '/dev/null']
19:41:23 [V      ] [5] Starting async job: ['golint', '/Users/nukr/workspace/gocode/src/github.com/nukr/gopl/04_composite_types/exercises/06_squash_spaces/squashspace_test.go']
19:41:23 [V      ] [5] Starting async job: ['go', 'vet']
19:41:23 [D +0.33] [5.3] exit: golint: 0
19:41:23 [D      ] [5.3] golint: completed with exit code 0.
19:41:23 [D      ] [5.3] Cleaning jobinfo
19:41:23 [D      ] Skipping User autocmd NeomakeJobFinished: no hooks.
19:41:23 [D      ] [5.2] stderr: go: ['# github.com/nukr/gopl/04_composite_types/exercises/06_squash_spaces', './squashspace.go:4: missing return at end of function', './squashspace_test.go:8: cannot use actual (type string) as type []byte in argument to squashspace', './squashspace_test.go:8: cannot use squashspace(actual) (type []byte) as type string in assignment', '']
19:41:23 [D      ] [5.4] exit: govet: 0
19:41:23 [D      ] [5.4] govet: completed with exit code 0.
19:41:23 [D      ] [5.4] Cleaning jobinfo
19:41:23 [D      ] Skipping User autocmd NeomakeJobFinished: no hooks.
19:41:23 [D      ] [5.2] exit: go: 2
19:41:23 [D      ] [5.2] go: processing 4 lines of output.
19:41:23 [D      ] Placing sign: sign place 5000 line=4 name=neomake_err buffer=3
19:41:23 [D      ] Placing sign: sign place 5000 line=8 name=neomake_err buffer=1
19:41:23 [D      ] Placing sign: sign place 5000 name=neomake_err buffer=1
19:41:23 [D      ] Skipping User autocmd NeomakeCountsChanged: no hooks.
19:41:23 [D      ] [5.2] go: completed with exit code 2.
19:41:23 [D      ] [5.2] Cleaning jobinfo
19:41:23 [D      ] Skipping User autocmd NeomakeJobFinished: no hooks.
19:41:23 [D      ] File-level errors cleaned in buffer 1
19:41:23 [D      ] Skipping User autocmd NeomakeFinished: no hooks.
19:41:24 [D +0.80] [6] Nothing to make: no enabled file mode makers.
19:41:25 [D +0.48] [7] Nothing to make: no enabled file mode makers.
19:41:25 [D +0.03] Skipping User autocmd NeomakeCountsChanged: no hooks.
19:41:25 [D      ] [8] Running makers: go (auto), golint (auto), govet (auto)
19:41:25 [V      ] [8] Starting async job: ['go', 'test', '-c', '-o', '/dev/null']
19:41:25 [V      ] [8] Starting async job: ['golint', '/Users/nukr/workspace/gocode/src/github.com/nukr/gopl/04_composite_types/exercises/06_squash_spaces/squashspace.go']
19:41:25 [V      ] [8] Starting async job: ['go', 'vet']
19:41:25 [D +0.32] [8.9] exit: golint: 0
19:41:25 [D      ] [8.9] golint: completed with exit code 0.
19:41:25 [D      ] [8.9] Cleaning jobinfo
19:41:25 [D      ] Skipping User autocmd NeomakeJobFinished: no hooks.
19:41:25 [D      ] [8.8] stderr: go: ['# github.com/nukr/gopl/04_composite_types/exercises/06_squash_spaces', './squashspace.go:4: missing return at end of function', './squashspace_test.go:8: cannot use actual (type string) as type []byte in argument to squashspace', './squashspace_test.go:8: cannot use squashspace(actual) (type []byte) as type string in assignment', '']
19:41:25 [D      ] [8.10] exit: govet: 0
19:41:25 [D      ] [8.10] govet: completed with exit code 0.
19:41:25 [D      ] [8.10] Cleaning jobinfo
19:41:25 [D      ] Skipping User autocmd NeomakeJobFinished: no hooks.
19:41:25 [D      ] [8.8] exit: go: 2
19:41:25 [D      ] [8.8] go: processing 4 lines of output.
19:41:25 [D      ] File-level errors cleaned in buffer 3
19:41:25 [D      ] Cleaning old signs in buffer 3:  {3: {4: 5000}}
19:41:25 [D      ] Unplacing sign: sign unplace 5000 buffer=3
19:41:25 [D      ] Placing sign: sign place 5000 line=4 name=neomake_err buffer=3
19:41:25 [D      ] Placing sign: sign place 5000 name=neomake_err buffer=1
19:41:25 [D      ] Placing sign: sign place 5000 name=neomake_err buffer=1
19:41:25 [D      ] Skipping User autocmd NeomakeCountsChanged: no hooks.
19:41:25 [D      ] [8.8] go: completed with exit code 2.
19:41:25 [D      ] [8.8] Cleaning jobinfo
19:41:25 [D      ] Skipping User autocmd NeomakeJobFinished: no hooks.
19:41:25 [D      ] Skipping User autocmd NeomakeFinished: no hooks.
19:41:26 [D +1.07] [9] Nothing to make: no enabled file mode makers.
19:41:27 [D +0.33] Skipping User autocmd NeomakeCountsChanged: no hooks.
19:41:27 [D      ] [10] Running makers: go (auto), golint (auto), govet (auto)
19:41:27 [V      ] [10] Starting async job: ['go', 'test', '-c', '-o', '/dev/null']
19:41:27 [V      ] [10] Starting async job: ['golint', '/Users/nukr/workspace/gocode/src/github.com/nukr/gopl/04_composite_types/exercises/06_squash_spaces/squashspace_test.go']
19:41:27 [V      ] [10] Starting async job: ['go', 'vet']
19:41:27 [D +0.06] [11] Running makers: go (auto), golint (auto), govet (auto)
19:41:27 [V      ] [11] Restarting already running job (10.14) for the same maker.
19:41:27 [D      ] [10.14] Stopping job
19:41:27 [V      ] [11] Restarting already running job (10.15) for the same maker.
19:41:27 [D      ] [10.15] Stopping job
19:41:27 [V      ] [11] Restarting already running job (10.16) for the same maker.
19:41:27 [D      ] [10.16] Stopping job
19:41:27 [D +0.07] [10.15] exit: job is restarting.
19:41:27 [V      ] [11] Starting async job: ['golint', '/Users/nukr/workspace/gocode/src/github.com/nukr/gopl/04_composite_types/exercises/06_squash_spaces/squashspace_test.go']
19:41:27 [D      ] [10.16] exit: job is restarting.
19:41:27 [V      ] [11] Starting async job: ['go', 'vet']
19:41:27 [D +0.02] [10.14] stderr: go: ['# github.com/nukr/gopl/04_composite_types/exercises/06_squash_spaces', './squashspace.go:4: missing return at end of function', './squashspace_test.go:8: cannot use actual (type string) as type []byte in argument to squashspace', './squashspace_test.go:8: cannot use squashspace(actual) (type []byte) as type string in assignment', '']
19:41:27 [D      ] [11.18] exit: golint: 0
19:41:27 [D      ] [11.18] golint: completed with exit code 0.
19:41:27 [D      ] [11.18] Cleaning jobinfo
19:41:27 [D      ] Skipping User autocmd NeomakeJobFinished: no hooks.
19:41:27 [D      ] [10.14] exit: job is restarting.
19:41:27 [V      ] [11] Starting async job: ['go', 'test', '-c', '-o', '/dev/null']
19:41:27 [D +0.10] [11.19] exit: govet: 0
19:41:27 [D      ] [11.19] govet: completed with exit code 0.
19:41:27 [D      ] [11.19] Cleaning jobinfo
19:41:27 [D      ] Skipping User autocmd NeomakeJobFinished: no hooks.
19:41:27 [D +0.03] [11.20] stderr: go: ['# github.com/nukr/gopl/04_composite_types/exercises/06_squash_spaces', './squashspace.go:4: missing return at end of function', './squashspace_test.go:8: cannot use actual (type string) as type []byte in argument to squashspace', './squashspace_test.go:8: cannot use squashspace(actual) (type []byte) as type string in assignment', '']
19:41:27 [D      ] [11.20] exit: go: 2
19:41:27 [D      ] [11.20] go: processing 4 lines of output.
19:41:27 [D      ] Placing sign: sign place 5000 name=neomake_err buffer=3
19:41:27 [D      ] Placing sign: sign place 5000 line=8 name=neomake_err buffer=1
19:41:27 [D      ] Placing sign: sign place 5000 name=neomake_err buffer=1
19:41:27 [D      ] Skipping User autocmd NeomakeCountsChanged: no hooks.
19:41:27 [D      ] [11.20] go: completed with exit code 2.
19:41:27 [D      ] [11.20] Cleaning jobinfo
19:41:27 [D      ] Skipping User autocmd NeomakeJobFinished: no hooks.
19:41:27 [D      ] File-level errors cleaned in buffer 1
19:41:27 [D      ] Cleaning old signs in buffer 1:  {1: {8: 5000}}
19:41:27 [D      ] Unplacing sign: sign unplace 5000 buffer=1
19:41:27 [D      ] Skipping User autocmd NeomakeFinished: no hooks.
19:41:28 [D +0.78] [12] Nothing to make: no enabled file mode makers.
19:41:28 [D +0.63] Skipping User autocmd NeomakeCountsChanged: no hooks.
19:41:28 [D      ] [13] Running makers: go (auto), golint (auto), govet (auto)
19:41:28 [V      ] [13] Starting async job: ['go', 'test', '-c', '-o', '/dev/null']
19:41:28 [V      ] [13] Starting async job: ['golint', '/Users/nukr/workspace/gocode/src/github.com/nukr/gopl/04_composite_types/exercises/06_squash_spaces/squashspace.go']
19:41:28 [V      ] [13] Starting async job: ['go', 'vet']
19:41:28 [D +0.07] [14] Running makers: go (auto), golint (auto), govet (auto)
19:41:28 [V      ] [14] Restarting already running job (13.21) for the same maker.
19:41:28 [D      ] [13.21] Stopping job
19:41:28 [V      ] [14] Restarting already running job (13.22) for the same maker.
19:41:28 [D      ] [13.22] Stopping job
19:41:28 [V      ] [14] Restarting already running job (13.23) for the same maker.
19:41:28 [D      ] [13.23] Stopping job
19:41:28 [D +0.07] [13.22] exit: job is restarting.
19:41:28 [V      ] [14] Starting async job: ['golint', '/Users/nukr/workspace/gocode/src/github.com/nukr/gopl/04_composite_types/exercises/06_squash_spaces/squashspace.go']
19:41:28 [D      ] [13.23] exit: job is restarting.
19:41:28 [V      ] [14] Starting async job: ['go', 'vet']
19:41:28 [D +0.01] [13.21] stderr: go: ['# github.com/nukr/gopl/04_composite_types/exercises/06_squash_spaces', './squashspace.go:4: missing return at end of function', './squashspace_test.go:8: cannot use actual (type string) as type []byte in argument to squashspace', './squashspace_test.go:8: cannot use squashspace(actual) (type []byte) as type string in assignment', '']
19:41:28 [D      ] [14.25] exit: golint: 0
19:41:28 [D      ] [14.25] golint: completed with exit code 0.
19:41:28 [D      ] [14.25] Cleaning jobinfo
19:41:28 [D      ] Skipping User autocmd NeomakeJobFinished: no hooks.
19:41:28 [D      ] [13.21] exit: job is restarting.
19:41:28 [V      ] [14] Starting async job: ['go', 'test', '-c', '-o', '/dev/null']
19:41:29 [D +0.10] [14.26] exit: govet: 0
19:41:29 [D      ] [14.26] govet: completed with exit code 0.
19:41:29 [D      ] [14.26] Cleaning jobinfo
19:41:29 [D      ] Skipping User autocmd NeomakeJobFinished: no hooks.
19:41:29 [D +0.03] [14.27] stderr: go: ['# github.com/nukr/gopl/04_composite_types/exercises/06_squash_spaces', './squashspace.go:4: missing return at end of function', './squashspace_test.go:8: cannot use actual (type string) as type []byte in argument to squashspace', './squashspace_test.go:8: cannot use squashspace(actual) (type []byte) as type string in assignment', '']
19:41:29 [D      ] [14.27] exit: go: 2
19:41:29 [D      ] [14.27] go: processing 4 lines of output.
19:41:29 [D      ] File-level errors cleaned in buffer 3
19:41:29 [D      ] Cleaning old signs in buffer 3:  {3: {4: 5000}}
19:41:29 [D      ] Unplacing sign: sign unplace 5000 buffer=3
19:41:29 [D      ] Placing sign: sign place 5000 line=4 name=neomake_err buffer=3
19:41:29 [D      ] Placing sign: sign place 5000 name=neomake_err buffer=1
```

**Comment by blueyed** [comment] 2017-03-12 15:47
Thanks for the detailed information.
Maybe https://github.com/neomake/neomake/pull/1101 will help, but otherwise I have some rewrite of the signs handling somewhere in my stashes, too - but that might take a while until I get back to it.

The problem here seems to be that the sign is cleared/unplaced for buffer 1, but later it is trying to upgrade it to an error sign (can be seen since `line=X` is missing there).

```
19:41:27 [D      ] [11.20] Cleaning jobinfo
19:41:27 [D      ] Skipping User autocmd NeomakeJobFinished: no hooks.
19:41:27 [D      ] File-level errors cleaned in buffer 1
19:41:27 [D      ] Cleaning old signs in buffer 1:  {1: {8: 5000}}
19:41:27 [D      ] Unplacing sign: sign unplace 5000 buffer=1
…
19:41:29 [D      ] Unplacing sign: sign unplace 5000 buffer=3
19:41:29 [D      ] Placing sign: sign place 5000 line=4 name=neomake_err buffer=3
19:41:29 [D      ] Placing sign: sign place 5000 name=neomake_err buffer=1
```

**Comment by nukr** [comment] 2017-03-12 16:02
Thanks your rapid response but it's seems not work for me after #1101 .

Is there a workaround for this issue ?

**Comment by ivegotasthma** [comment] 2017-03-12 16:26
For me this started happening 3 days ago, I don't know how to see which commit caused the issue.

**Comment by blueyed** [comment] 2017-03-12 23:25
If it only started recently, then it would be useful to see which commit caused it, i.e. use git-bisect to find it.
It might be related to how makers are restarted, and https://github.com/neomake/neomake/pull/1092 might fix it.
A good workaround might be to not call Neomake on Buf(Win)Enter, but only on BufWritePost.

**Comment by blueyed** [comment] 2017-03-14 20:14
https://github.com/neomake/neomake/pull/1092 is merged now.

**Comment by nukr** [comment] 2017-03-15 04:30
After update error still occurs.

Thanks for your effort anyway.

**Comment by blueyed** [comment] 2017-03-17 21:45
There have been more fixes regarding parallel makes by now.
Please retry.

Otherwise I think we have to wait until I get down to the signs fixes I have.

**Comment by sbl** [comment] 2017-03-18 09:27
I can just report that I had similar issues for about a month now. Currently using the `flow` for javascript.

I retried this on master (current hash d6fddefb253e348c6980fd8a43ddb285c747cc14) and get a similar output (excuse the german locale, but it is more or less the same error that is reported originally).

It is hard to give exact steps to reproduce but it happens after saving a couple of times and having multiple flow based errors.

```
Fehler beim Ausführen von "function <SNR>80_exit_handler[37]..<SNR>80_RegisterJobOutput[
19]..<SNR>80_ProcessJobOutput[29]..<SNR>80_AddExprCallback[103]..neomake#signs#PlaceSign
":
Zeile   30:
E885: Zeichen neomake_err kann nicht verändert werden
```

**Comment by blueyed** [comment] 2017-09-07 21:23
I think and hope fdd47d42 might have fixed this.

Please re-open let me know if you are still seeing this.

**Closed by blueyed** 2017-09-07 21:23 UTC
Labels: bug
