### ISSUE TITLE
neomake#highlights#ShowHighlights[4]..<SNR>90_ResetHighlights error message

### ISSUE THREAD

**Issue by gmathews** [neomake/neomake#883] opened 2016-12-22 02:09 UTC
When switching to another buffer, a lot of errors appear at the bottom like:
```
Error detected while processing function neomake#highlights#ShowHighlights[4]..<SNR>90_ResetHighlights:
line    6:
E803: ID not found: 12
Error detected while processing function neomake#ProcessPendingOutput[11]..neomake#highlights#ShowHighlights[4]..<SNR>90_ResetHighlights:
line    6:
E803: ID not found: 12
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Dec 12 2016 16:12:59)
E16: Invalid range
Error detected while processing function neomake#highlights#ShowHighlights[4]..<SNR>90_ResetHighlights:
line    6:
E803: ID not found: 12
"ic_blueprint/mission_data.py" line 1 of 182 --0%-- col 1
Error detected while processing function neomake#ProcessPendingOutput[11]..neomake#highlights#ShowHighlights[4]..<SNR>90_ResetHighlights:
line    6:
E803: ID not found: 12 
```
### Expected behavior

Reset highlights doesn't show errors each time I leave a buffer for another.
### Steps to reproduce
Open a buffer you can lint, run :Neomake on it, open another buffer you can lint and do the same, when you go to a third buffer you cannot lint, the errors seem to appear.

Relevant part of vimrc:
```
let g:neomake_verbose=3
let g:neomake_python_enabled_makers = ['pylint', 'flake8']
autocmd BufWritePost,BufReadPost * Neomake
let g:neomake_error_sign = { 'text': ">>", 'texthl': 'NeoMakeErrorDefault' }
let g:neomake_warning_sign = { 'text': ">>", 'texthl': 'NeoMakeWarningDefault' }
let g:neomake_informational_sign = { 'text': "\uF05A", 'texthl': 'NeomakeInformationDefault' }
let g:neomake_message_sign = { 'text': "\uF09A", 'texthl': 'NeomakeMessageDefault' }
```

#### Neomake debug information
Async support: 1
Current filetype: python

##### Enabled makers
For the current filetype (with :Neomake):
 - pylint
   postprocess: function('neomake#makers#ft#python#PylintEntryProcess')
   errorformat: '%A%f:%l:%c:%t: %m,%A%f:%l: %m,%A%f:(%l): %m,%-Z%p^%.%#,%-G%.%#'
   args: ['--output-format=text', '--msg-template="{path}:{line}:{column}:{C}: [{symbol}] {msg}"', '--reports=no']
   exe: 'pylint'
 - flake8
   postprocess: function('neomake#makers#ft#python#Flake8EntryProcess')
   errorformat: '%E%f:%l: could not compile,%-Z%p^,%A%f:%l:%c: %t%n %m,%A%f:%l: %t%n %m,%-G%.%#'
   args: ['--format=default']
   exe: 'flake8'
NOTE: you can define g:neomake_python_enabled_makers to configure it (or b:neomake_python_enabled_makers).

For the project (with :Neomake!): None.
NOTE: you can define g:neomake_enabled_makers to configure it.

Default maker settings:
 - remove_invalid_entries: 1
 - buffer_output: 1

##### Settings
```
g:neomake_informational_sign = {'texthl': 'NeomakeInformationDefault', 'text': ''}
g:neomake_error_sign = {'texthl': 'NeoMakeErrorDefault', 'text': '>>'}
g:neomake_verbose = 3
g:neomake_place_signs = 1
g:neomake_message_sign = {'texthl': 'NeomakeMessageDefault', 'text': ''}
g:neomake_python_enabled_makers = ['pylint', 'flake8']
g:neomake_warning_sign = {'texthl': 'NeoMakeWarningDefault', 'text': '>>'}


shell: /bin/zsh
shellcmdflag: -c
Windows: 0
```

#### :version
```

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Dec 12 2016 16:12:59)
MacOS X (unix) version
Included patches: 1-124
Compiled by Homebrew
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl             +cmdline_compl   +digraphs        +folding         +lambda          +mouse           +multi_lang      +profile         +statusline      +timers          +wildignore      
+arabic          +cmdline_hist    +dnd             -footer          +langmap         +mouseshape      -mzscheme        +python          -sun_workshop    +title           +wildmenu        
+autocmd         +cmdline_info    -ebcdic          +fork()          +libcall         +mouse_dec       +netbeans_intg   -python3         +syntax          +toolbar         +windows         
+balloon_eval    +comments        +emacs_tags      +fullscreen      +linebreak       -mouse_gpm       +num64           +quickfix        +tag_binary      +transparency    +writebackup     
+browse          +conceal         +eval            -gettext         +lispindent      -mouse_jsbterm   +odbeditor       +reltime         +tag_old_static  +user_commands   -X11             
++builtin_terms  +cryptv          +ex_extra        -hangul_input    +listcmds        +mouse_netterm   +packages        +rightleft       -tag_any_white   +vertsplit       -xfontset        
+byte_offset     +cscope          +extra_search    +iconv           +localmap        +mouse_sgr       +path_extra      +ruby            +tcl             +virtualedit     +xim             
+channel         +cursorbind      +farsi           +insert_expand   -lua             -mouse_sysmouse  +perl            +scrollbind      +termguicolors   +visual          -xpm             
+cindent         +cursorshape     +file_in_path    +job             +menu            +mouse_urxvt     +persistent_undo +signs           +terminfo        +visualextra     -xsmp            
+clientserver    +dialog_con_gui  +find_in_path    +jumplist        +mksession       +mouse_xterm     +postscript      +smartindent     +termresponse    +viminfo         -xterm_clipboard 
+clipboard       +diff            +float           +keymap          +modify_fname    +multi_byte      +printer         +startuptime     +textobjects     +vreplace        -xterm_save      
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/Applications/MacVim.app/Contents/Resources/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X_UNIX  -F/usr/local/opt/python/Frameworks -I/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/include/python2.7 -fno-strict-aliasing -fno-common -dynamic -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: clang   -L. -L/usr/local/lib -L. -L/usr/local/lib -F/usr/local/opt/python/Frameworks -L/usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config -lpython2.7 -framework CoreFoundation -L/usr/local/lib -o Vim -framework Cocoa -framework Carbon       -lm  -lncurses -liconv -framework Cocoa   -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -lperl -F/usr/local/opt/python/Frameworks -framework Python  -F/System/Library/Frameworks -framework Tcl -framework CoreFoundation -framework Ruby    
```

#### :messages
```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
"~/devel/Whiplash-Server/src/slots/wp_missions/mission_selector.py" 130L, 4722C
Neomake [6.686]: [1] Running makers: pylint, flake8 ([{'postprocess': function('neomake#makers#ft#python#PylintEntryProcess'), 'ft': 'python', 'errorformat': '%A%f:%l:%c:%t: %m,%A%f:%l: %m,%A%f:(%l): %m,%-Z%p^%.%#,%-G%.%#', 'args': ['--output-format=text', '--msg-template="{path}:{line}:{column}:{C}: [{symbol}] {msg}"', '--reports=no'], 'exe': 'pylint', 'remove_invalid_entries': 1, 'buffer_output': 1, 'name': 'pylint'}, {'postprocess': function('neomake#makers#ft#python#Flake8EntryProcess'), 'ft': 'python', 'errorformat': '%E%f:%l: could not compile,%-Z%p^,%A%f:%l:%c: %t%n %m,%A%f:%l: %t%n %m,%-G%.%#', 'args': ['--format=default'], 'exe': 'flake8', 'remove_invalid_entries': 1, 'buffer_output': 1, 'name': 'flake8'}])
Neomake [6.686]: [1] Starting async job: ['pylint', '--output-format=text', '--msg-template="{path}:{line}:{column}:{C}: [{symbol}] {msg}"', '--reports=no', '/Users/george/devel/Whiplash-Server/src/slots/wp_missions/mission_selector.py']
Neomake [6.689]: [1.0] Vim job: {'status': 'run', 'stoponexit': 'term', 'exitval': 0, 'exit_cb': 0, 'channel': channel 0 open, 'process': 19366}
Neomake [6.689]: [1.0] Vim channel: {'status': 'open', 'id': 0, 'in_io': 'pipe', 'err_mode': 'RAW', 'in_status': 'open', 'out_io': 'pipe', 'err_io': 'pipe', 'err_status': 'open', 'out_timeout': 2000, 'out_status': 'open', 'out_mode': 'RAW', 'in_mode': 'RAW', 'in_timeout': 2000, 'err_timeout': 2000}
Neomake [6.690]: [1] Starting async job: ['flake8', '--format=default', '/Users/george/devel/Whiplash-Server/src/slots/wp_missions/mission_selector.py']
Neomake [6.691]: [1.1] Vim job: {'status': 'run', 'stoponexit': 'term', 'exitval': 0, 'exit_cb': 0, 'channel': channel 1 open, 'process': 19368}
Neomake [6.692]: [1.1] Vim channel: {'status': 'open', 'id': 1, 'in_io': 'pipe', 'err_mode': 'RAW', 'in_status': 'open', 'out_io': 'pipe', 'err_io': 'pipe', 'err_status': 'open', 'out_timeout': 2000, 'out_status': 'open', 'out_mode': 'RAW', 'in_mode': 'RAW', 'in_timeout': 2000, 'err_timeout': 2000}
Neomake [6.961]: [1.1] MakeHandlerVim: stdout: channel 1 open, '/Users/george/devel/Whiplash-Server/src/slots/wp_missions/mission_selector.py:14:1: F811 redefinition of unused ''MissionInfo'' from line 9^@'
Neomake [6.962]: [1.1] stdout: flake8: ['/Users/george/devel/Whiplash-Server/src/slots/wp_missions/mission_selector.py:14:1: F811 redefinition of unused ''MissionInfo'' from line 9', '']
Neomake [6.981]: [1.1] MakeHandlerVim: exit: channel 1 closed, job_info: {'status': 'dead', 'stoponexit': 'term', 'exitval': 1, 'exit_cb': 0, 'channel': channel 1 closed, 'process': 19368}
Neomake [6.981]: [1.1] exit: flake8: 1
Neomake [6.982]: Not processing output for mode r
Neomake [6.982]: [1.1] flake8: completed with exit code 1.
Neomake [6.983]: [1.1] Output left to be processed, not cleaning job yet.
Neomake [7.232]: [1.0] MakeHandlerVim: stdout: channel 0 open, '************* Module slots.wp_missions.mission_selector^@wp_missions/mission_selector.py:107:0:W: [fixme] TODO: Select per criteria^@wp_missions/mission_selector.py:122:0:W: [fixme] TODO: Select per criteria^@wp_missions/mission_selector.py:83:0:C: [line-too-long] Line too long (117/100)^@wp_missions/mission_selector.py:14:0:W: [reimported] Reimport ''MissionInfo'' (imported line 9)^@wp_missions/mission_selector.py:38:4:W: [dangerous-default-value] Dangerous default value [] as argument^@wp_missions/mission_selector.py:38:4:C: [invalid-name] Invalid argument name "choose_LTE"^@wp_missions/mission_selector.py:82:16:C: [invalid-name] Invalid variable name "condA"^@wp_missions/mission_selector.py:10:0:C: [wrong-import-order] standard import "from datetime import datetime" comes before "from ic_blueprint.mission_data import MissionInfo"^@wp_missions/mission_selector.py:11:0:C: [wrong-import-order] standard import "import random" comes before "from ic_blueprint.mission_data import MissionInfo"^@'
Neomake [7.232]: [1.0] stdout: pylint: ['************* Module slots.wp_missions.mission_selector', 'wp_missions/mission_selector.py:107:0:W: [fixme] TODO: Select per criteria', 'wp_missions/mission_selector.py:122:0:W: [fixme] TODO: Select per criteria', 'wp_missions/mission_selector.py:83:0:C: [line-too-long] Line too long (117/100)', 'wp_missions/mission_selector.py:14:0:W: [reimported] Reimport ''MissionInfo'' (imported line 9)', 'wp_missions/mission_selector.py:38:4:W: [dangerous-default-value] Dangerous default value [] as argument', 'wp_missions/mission_selector.py:38:4:C: [invalid-name] Invalid argument name "choose_LTE"', 'wp_missions/mission_selector.py:82:16:C: [invalid-name] Invalid variable name "condA"', 'wp_missions/mission_selector.py:10:0:C: [wrong-import-order] standard import "from datetime import datetime" comes before "from ic_blueprint.mission_data import MissionInfo"', 'wp_missions/mission_selector.py:11:0:C: [wrong-import-order] standard import "import random" comes before "from ic_blueprint.mission_data import MissionInfo"', '']
Neomake [7.255]: [1.0] MakeHandlerVim: exit: channel 0 closed, job_info: {'status': 'dead', 'stoponexit': 'term', 'exitval': 20, 'exit_cb': 0, 'channel': channel 0 closed, 'process': 19366}
Neomake [7.255]: [1.0] exit: pylint: 20
Neomake [7.255]: Not processing output for mode r
Neomake [7.256]: [1.0] pylint: completed with exit code 20.
Neomake [7.256]: [1.0] Output left to be processed, not cleaning job yet.
Neomake [15.428]: [1.0] pylint: processing 10 lines of output.
Neomake [15.432]: File-level errors cleaned in buffer 1
Neomake [15.434]: Skipping User autocmd NeomakeCountsChanged: no hooks.
Neomake [15.435]: [1.0] Processed pending output
Neomake [15.435]: Skipping User autocmd NeomakeJobFinished: no hooks.
Neomake [15.435]: [1.1] flake8: processing 1 lines of output.
Neomake [15.436]: Skipping User autocmd NeomakeCountsChanged: no hooks.
Neomake [15.436]: [1.1] Processed pending output
Neomake [15.447]: Skipping User autocmd NeomakeJobFinished: no hooks.
Neomake [15.447]: Skipping User autocmd NeomakeFinished: no hooks.
Neomake [19.197]: Placing sign: sign place 5000 line=82 name=neomake_warn buffer=1
Neomake [19.208]: Placing sign: sign place 5001 line=83 name=neomake_warn buffer=1
Neomake [19.209]: Placing sign: sign place 5002 line=107 name=neomake_warn buffer=1
Neomake [19.209]: Placing sign: sign place 5003 line=122 name=neomake_warn buffer=1
"~/devel/Whiplash-Server/src/slots/ic_blueprint/mission_data.py" 182L, 6692C
Neomake [23.765]: [2] Running makers: pylint, flake8 ([{'postprocess': function('neomake#makers#ft#python#PylintEntryProcess'), 'ft': 'python', 'errorformat': '%A%f:%l:%c:%t: %m,%A%f:%l: %m,%A%f:(%l): %m,%-Z%p^%.%#,%-G%.%#', 'args': ['--output-format=text', '--msg-template="{path}:{line}:{column}:{C}: [{symbol}] {msg}"', '--reports=no'], 'exe': 'pylint', 'remove_invalid_entries': 1, 'buffer_output': 1, 'name': 'pylint'}, {'postprocess': function('neomake#makers#ft#python#Flake8EntryProcess'), 'ft': 'python', 'errorformat': '%E%f:%l: could not compile,%-Z%p^,%A%f:%l:%c: %t%n %m,%A%f:%l: %t%n %m,%-G%.%#', 'args': ['--format=default'], 'exe': 'flake8', 'remove_invalid_entries': 1, 'buffer_output': 1, 'name': 'flake8'}])
Neomake [34.085]: [2] Starting async job: ['pylint', '--output-format=text', '--msg-template="{path}:{line}:{column}:{C}: [{symbol}] {msg}"', '--reports=no', '/Users/george/devel/Whiplash-Server/src/slots/ic_blueprint/mission_data.py']
Neomake [38.054]: [2.4] Vim job: {'status': 'run', 'stoponexit': 'term', 'exitval': 0, 'exit_cb': 0, 'channel': channel 4 open, 'process': 19394}
Neomake [38.054]: [2.4] Vim channel: {'status': 'open', 'id': 4, 'in_io': 'pipe', 'err_mode': 'RAW', 'in_status': 'open', 'out_io': 'pipe', 'err_io': 'pipe', 'err_status': 'open', 'out_timeout': 2000, 'out_status': 'open', 'out_mode': 'RAW', 'in_mode': 'RAW', 'in_timeout': 2000, 'err_timeout': 2000}
Neomake [38.626]: [2.4] MakeHandlerVim: stdout: channel 4 open, '************* Module slots.ic_blueprint.mission_data^@ic_blueprint/mission_data.py:64:0:W: [fixme] TODO: filter by schedule^@ic_blueprint/mission_data.py:68:0:W: [fixme] TODO: faster method Filter list^@ic_blueprint/mission_data.py:87:0:W: [fixme] TODO: faster method Filter list^@ic_blueprint/mission_data.py:109:0:W: [fixme] TODO: do we need to support multiple rewards?^@ic_blueprint/mission_data.py:73:0:C: [line-too-long] Line too long (102/100)^@ic_blueprint/mission_data.py:1:0:W: [relative-import] Relative import ''base_multivariate_class'', should be ''slots.ic_blueprint.base_multivariate_class''^@ic_blueprint/mission_data.py:29:22:W: [cell-var-from-loop] Cell variable mission_json defined in loop^@ic_blueprint/mission_data.py:81:16:W: [redefined-builtin] Redefining built-in ''max''^@ic_blueprint/mission_data.py:80:16:W: [redefined-builtin] Redefining built-in ''min''^@ic_blueprint/mission_data.py:119:4:R: [no-self-use] Method could be a function^@ic_blueprint/mission_data.py:126:4:R: [no-self-use] Method could be a function^@ic_blueprint/mission_data.py:137:4:C: [old-style-class] Old-style class defined.^@ic_blueprint/mission_data.py:137:4:R: [too-few-public-methods] Too few public methods (0/2)^@ic_blueprint/mission_data.py:170:20:W: [attribute-defined-outside-init] Attribute ''_active_bag_id'' defined outside __init__^@ic_blueprint/mission_data.py:177:12:W: [attribute-defined-outside-init] Attribute ''_active_bag_id'' defined outside __init__^@ic_blueprint/mission_data.py:2:0:C: [wrong-import-order] standard import "from datetime import datetime" comes before "from base_multivariate_class import BaseMultivariateClass"^@'
Neomake [38.629]: [2.4] stdout: pylint: ['************* Module slots.ic_blueprint.mission_data', 'ic_blueprint/mission_data.py:64:0:W: [fixme] TODO: filter by schedule', 'ic_blueprint/mission_data.py:68:0:W: [fixme] TODO: faster method Filter list', 'ic_blueprint/mission_data.py:87:0:W: [fixme] TODO: faster method Filter list', 'ic_blueprint/mission_data.py:109:0:W: [fixme] TODO: do we need to support multiple rewards?', 'ic_blueprint/mission_data.py:73:0:C: [line-too-long] Line too long (102/100)', 'ic_blueprint/mission_data.py:1:0:W: [relative-import] Relative import ''base_multivariate_class'', should be ''slots.ic_blueprint.base_multivariate_class''', 'ic_blueprint/mission_data.py:29:22:W: [cell-var-from-loop] Cell variable mission_json defined in loop', 'ic_blueprint/mission_data.py:81:16:W: [redefined-builtin] Redefining built-in ''max''', 'ic_blueprint/mission_data.py:80:16:W: [redefined-builtin] Redefining built-in ''min''', 'ic_blueprint/mission_data.py:119:4:R: [no-self-use] Method could be a function', 'ic_blueprint/mission_data.py:126:4:R: [no-self-use] Method could be a function', 'ic_blueprint/mission_data.py:137:4:C: [old-style-class] Old-style class defined.', 'ic_blueprint/mission_data.py:137:4:R: [too-few-public-methods] Too few public methods (0/2)', 'ic_blueprint/mission_data.py:170:20:W: [attribute-defined-outside-init] Attribute ''_active_bag_id'' defined outside __init__', 'ic_blueprint/mission_data.py:177:12:W: [attribute-defined-outside-init] Attribute ''_active_bag_id'' defined outside __init__', 'ic_blueprint/mission_data.py:2:0:C: [wrong-import-order] standard import "from datetime import datetime" comes before "from base_multivariate_class import BaseMultivariateClass"', '']
Neomake [38.648]: [2.4] MakeHandlerVim: exit: channel 4 closed, job_info: {'status': 'dead', 'stoponexit': 'term', 'exitval': 28, 'exit_cb': 0, 'channel': channel 4 closed, 'process': 19394}
Neomake [38.648]: [2.4] exit: pylint: 28
Neomake [38.648]: Not processing output for mode r
Neomake [38.650]: [2.4] No window found for output!
Neomake [38.650]: [2.4] pylint: completed with exit code 28.
Neomake [38.679]: File-level errors cleaned in buffer 3
Neomake [38.703]: Skipping User autocmd NeomakeJobFinished: no hooks.
Neomake [38.717]: Skipping User autocmd NeomakeFinished: no hooks.
Neomake [46.124]: [2] Starting async job: ['flake8', '--format=default', '/Users/george/devel/Whiplash-Server/src/slots/ic_blueprint/mission_data.py']
Neomake [46.126]: [2.5] Vim job: {'status': 'run', 'stoponexit': 'term', 'exitval': 0, 'exit_cb': 0, 'channel': channel 5 open, 'process': 19404}
Neomake [46.126]: [2.5] Vim channel: {'status': 'open', 'id': 5, 'in_io': 'pipe', 'err_mode': 'RAW', 'in_status': 'open', 'out_io': 'pipe', 'err_io': 'pipe', 'err_status': 'open', 'out_timeout': 2000, 'out_status': 'open', 'out_mode': 'RAW', 'in_mode': 'RAW', 'in_timeout': 2000, 'err_timeout': 2000}
Neomake [46.410]: [2.5] MakeHandlerVim: exit: channel 5 closed, job_info: {'status': 'dead', 'stoponexit': 'term', 'exitval': 0, 'exit_cb': 0, 'channel': channel 5 closed, 'process': 19404}
Neomake [46.411]: [2.5] exit: flake8: 0
Neomake [46.411]: [2.5] flake8: completed with exit code 0.
Neomake [46.412]: Skipping User autocmd NeomakeJobFinished: no hooks.
Neomake [46.412]: Skipping User autocmd NeomakeFinished: no hooks.
Already at oldest change
"~/.vimrc" 284L, 9007C
Neomake [51.074]: Nothing to make: no enabled makers.
Error detected while processing function neomake#highlights#ShowHighlights[4]..<SNR>90_ResetHighlights:
line    6:
E803: ID not found: 12
Error detected while processing function neomake#ProcessPendingOutput[11]..neomake#highlights#ShowHighlights[4]..<SNR>90_ResetHighlights:
line    6:
E803: ID not found: 12
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Dec 12 2016 16:12:59)
E16: Invalid range
Error detected while processing function neomake#highlights#ShowHighlights[4]..<SNR>90_ResetHighlights:
line    6:
E803: ID not found: 12
"ic_blueprint/mission_data.py" line 1 of 182 --0%-- col 1
Error detected while processing function neomake#ProcessPendingOutput[11]..neomake#highlights#ShowHighlights[4]..<SNR>90_ResetHighlights:
line    6:
E803: ID not found: 12
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Dec 12 2016 16:12:59)
Error detected while processing function neomake#ProcessPendingOutput[11]..neomake#highlights#ShowHighlights[4]..<SNR>90_ResetHighlights:
line    6:
E803: ID not found: 12
```

**Comment by blueyed** [comment] 2016-12-22 02:27
Error seems to come from Vim's `matchdelete`: https://github.com/neomake/neomake/blob/b28c6651046f2bce590a2d832238d967ddfa8226/autoload/neomake/highlights.vim#L112.

@paretje 
Can you see what happens here?

**Comment by gmathews** [comment] 2016-12-23 23:57
I've been doing a little bit of investigating. This problem started occurring fairly recently when highlighting of the buffer started. I remember because I thought it was really cool and I missed it from syntastic. I rolled back to commit 115508f53c44a1aa4a7623e0223a792c8b02cecc and the problem seems to have gone away. I'm gonna try walking forward to see where it starts breaking.

**Comment by blueyed** [comment] 2016-12-24 01:17
You could also try https://github.com/neomake/neomake/pull/867, which is going to be merged soon.
Also try with just BufWritePost auto command etc.

**Comment by marlun** [comment] 2016-12-29 06:41
I'm also getting a lot of these errors. Is the recommended solution to go back to an earlier commit or wait for #867?

**Comment by blueyed** [comment] 2016-12-29 10:58
Could you git-bisect it, please?

**Comment by blueyed** [comment] 2017-01-03 14:03
Still an issue?
Might be fixed by https://github.com/neomake/neomake/pull/903 also already.

**Comment by gmathews** [comment] 2017-01-03 19:57
Sorry I was out of town. I just updated to the latest commit which has #903 merged in and the issue is still occurring. I'll git bisect a shot and see where it could be occurring.

**Comment by marlun** [comment] 2017-01-04 20:41
I'm getting

    Error detected while processing function neomake#highlights#ShowHighlights[4]<SNR>54_ResetHighlights:
    line    6:
    E803: ID not found: 5

on d66e499 If I:

1. Open a file without errors
2. Split it with `:vs`
3. Move to the right winow and open a file with errors `:e filewitherror.js`
4. Move to the left window
5. Move back to the right window with the file with errors
6. The error above is shown

**Comment by marlun** [comment] 2017-01-07 14:12
I'm not sure this is a neomake problem. I'm thinking it's my plugin for opening files that's messing with the matches. I'm saying matches without having a good understanding but if I only use regular vim commands like :edit and :buffer I never seem to get any problems but when I use `:Niffler .` (https://github.com/pgdouyon/vim-niffler) the problems starts. In its source I can see it also uses matchdelete (https://github.com/pgdouyon/vim-niffler/blob/master/autoload/niffler.vim#L392) not sure if that can have anything to do with this?

**Comment by blueyed** [comment] 2017-01-07 14:26
@marlun 
Without looking at the provided source, it sounds suspicious.
Are you using Vim? (like the OP)
Neomake uses some better/different API with Neovim, so that's why I (and others) might not see this issue.

A minimal test case (with a minimal vimrc) would be good to have.
I could not reproduce it with Vim based on your description in https://github.com/neomake/neomake/issues/883#issuecomment-270480811.

**Comment by marlun** [comment] 2017-01-08 09:58
I created an issue https://github.com/pgdouyon/vim-niffler/issues/43 for Niffler and the fix by @pgdouyon seems to work great.

**Comment by blueyed** [comment] 2017-01-08 11:27
Interesting.
That would allow for reproducing it in a test probably.

@gmathews 
Is your issue also caused by some other plugin?

**Comment by pgdouyon** [comment] 2017-01-08 12:50
FWIW the bug in my plugin was caused by a call to `clearmatches()` which is why the match ID no longer existed when Neomake went to call `matchdelete()`.

Although I would actually recommend Neomake prepend `silent!` to the call to `matchdelete()` if you're going to be using `matchaddpos()`.  I realize it's a bit heavyhanded, but matches created with `matchaddpos()` can't be restored using `setmatches()` so any plugin that tries to temporarily clear the matches in a window could also trigger this bug.

I believe it's also the case that the only errors that will be thrown by `matchdelete()` and not `matchadd()` are ones where the match ID has already been removed.  In those cases ignoring the error should be harmless since the match will have been deleted either way.

Just my two cents, this is also how the matchparen plugin handles deleting matches as well (which I believe is the plugin `matchaddpos()` was designed for).

**Comment by blueyed** [comment] 2017-01-08 20:40
@pgdouyon 
Thanks a lot for analysis, which I agree with!

Do you feel like creating a PR to fix this?

**Comment by bradleyfalzon** [comment] 2017-03-09 02:19
Any thoughts if this could be resolved soon if we know what the issue is?

**Comment by blueyed** [comment] 2017-03-10 18:28
@bradleyfalzon 
For one, an updated stacktrace / error message would be useful, and then it's probably about starting here: https://github.com/neomake/neomake/blob/26e32ed992b88c1847ec428902659339bc6cda9b/autoload/neomake/highlights.vim#L84

If you can easily reproduce it like you've said, then it should also be easy to write a Vader test for it.
Do you have plugins that call `clearmatches()`?

(it is rather easy to trigger it by calling `clearmatches()` (like mentioned above))

A patch might start like this:
```diff
diff --git i/autoload/neomake/highlights.vim w/autoload/neomake/highlights.vim
index 847b8e37..25865426 100644
--- i/autoload/neomake/highlights.vim
+++ w/autoload/neomake/highlights.vim
@@ -84,7 +84,10 @@ else
     function! neomake#highlights#ShowHighlights() abort
         if exists('w:current_highlights')
             for l:highlight in w:current_highlights
-                call matchdelete(l:highlight)
+                try
+                    call matchdelete(l:highlight)
+                catch /^Vim\%((\a\+)\)\=:E803/
+                endtry
             endfor
         endif
         let w:current_highlights = []
```

**Comment by blueyed** [comment] 2017-03-10 18:29
@bradleyfalzon 
If you get the error, what does `:echo getmatches()` display?

**Closed** 2017-03-10 19:39 UTC
Labels: bug, vim-only

**Comment by bradleyfalzon** [comment] 2017-03-11 02:21
@blueyed I tested it quickly after #1102, and it looks to be resolved, is this your understanding too?

**Comment by gmathews** [comment] 2017-03-18 01:06
It seems to be fixed. Thanks everybody.
