### ISSUE TITLE
Error occurred during neomake#ProcessPendingOutput

### ISSUE THREAD

**Issue by scottgrayson** [neomake/neomake#894] opened 2016-12-24 22:49 UTC
Just installed and trying out for the first time. Linting works fine with php, but this error pops up while i am in command mode and not typing.

```
Error detected while processing function neomake#ProcessPendingOutput[4]..neomake#ProcessCu
rrentWindow[5]..<SNR>44_ProcessPendingOutput:
line    3:
E716: Key not present in Dictionary: 20
```
the key not present number is not always 20. it changes

```
#### Neomake debug information
Async support: 1
Current filetype: php

##### Enabled makers
For the current filetype (with :Neomake):
 - php
   postprocess: function('neomake#makers#ft#php#PhpEntryProcess')
   errorformat: '%m\ in\ %f\ on\ line\ %l,%-GErrors\ parsing\ %f,%-G'
   args: ['-l']
   exe: 'php'
NOTE: you can define g:neomake_php_enabled_makers to configure it (or b:neomake_php_enabled
_makers).
```

**Comment by blueyed** [comment] 2016-12-25 01:11
Thanks for the report!

1. please provide steps to reproduce this
2. please provide the output from `:verb NeomakeInfo` after `:let neomake_verbose = 3` and reproducing this afterwards

Also: on what events do you invoke `:Neomake`?

**Comment by ChrisBuchholz** [comment] 2016-12-28 10:32
I'm just gonna listen in on this since I experience it too using `Neomake! cargo` on `ButReadPre` and `BufWritePost`.

**Comment by scottgrayson** [comment] 2016-12-28 13:13
I havent been able to find a pattern for when this error happens. The plugin is still very usable.

`autocmd! BufWritePost,BufEnter * Neomake`

I'll update this comment with `:NeomakeInfo` output

**Comment by blueyed** [comment] 2016-12-28 21:21
https://github.com/neomake/neomake/pull/867 might fix it, if you want to test that branch/PR..

You could also enable the debug log, and post it here after it happens again.

**Comment by ChrisBuchholz** [comment] 2016-12-29 10:22
I have tried enabling the debug log by adding `let g:neomake_log='xxx'` to my settings, and the file gets populated alright, but the errors this issue is about I'm not able to find in the file.

The output I see above my cmd bar is:

```
Error detected while processing function neomake#ProcessPendingOutput[6]..<SNR>73_ProcessPendingOutput:
line    3:
E716: Key not present in Dictionary: 35
```

I have attached the log file.
[neomake.log.txt](https://github.com/neomake/neomake/files/676932/neomake.log.txt)

**Comment by blueyed** [comment] 2016-12-29 11:00
Yes, the error won't be logged.
Does the log end when the error happens?

Could you try to git-bisect the issue?

**Comment by blueyed** [comment] 2016-12-29 11:42
Relevant log entry (it is about job 35):

```
[2016-12-29T11:15:12+0100 @38.139, debug] [10] Running makers: cargo ([{'ft': '', 'errorformat': '%-Gerror: aborting due to previous error,%-Gerror: aborting due to %\\d%\\+ previous errors,
[2016-12-29T11:15:12+0100 @38.139, verb ] [10] Starting async job: ['cargo', 'check']
[2016-12-29T11:15:12+0100 @38.140, debug] [10.35] Vim job: {'status': 'run', 'stoponexit': 'term', 'exitval': 0, 'exit_cb': 0, 'channel': channel 35 open, 'process': 11755}
[2016-12-29T11:15:12+0100 @38.141, debug] [10.35] Vim channel: {'status': 'open', 'id': 35, 'in_io': 'pipe', 'err_mode': 'RAW', 'in_status': 'open', 'out_io': 'pipe', 'err_io': 'pipe', 'err_
[2016-12-29T11:15:12+0100 @38.508, debug] [10.35] MakeHandlerVim: stdout: channel 35 open, '   Compiling beersury-api v0.1.0 (file:///Users/cb/Projekter/Beersury-API-rust)^@'
[2016-12-29T11:15:12+0100 @38.508, debug] [10.35] stderr: cargo: ['   Compiling beersury-api v0.1.0 (file:///Users/cb/Projekter/Beersury-API-rust)', '']
[2016-12-29T11:15:13+0100 @39.757, debug] [10.35] MakeHandlerVim: stdout: channel 35 open, 'error[E0308]: mismatched types^@  --> src/views/account.rs:51:5^@   |^@51 |       insert(&new_acco
[2016-12-29T11:15:13+0100 @39.757, debug] [10.35] stderr: cargo: ['error[E0308]: mismatched types', '  --> src/views/account.rs:51:5', '   |', '51 |       insert(&new_account)', '   |  _____
[2016-12-29T11:15:13+0100 @39.758, debug] [10.35] MakeHandlerVim: stdout: channel 35 open, '   = note: expected type `std::result::Result<rocket::response::status::Created<std::string::Strin
[2016-12-29T11:15:13+0100 @39.759, debug] [10.35] stderr: cargo: ['   = note: expected type `std::result::Result<rocket::response::status::Created<std::string::String>, error::ApiError>`', '
[2016-12-29T11:15:13+0100 @39.839, debug] [10.35] MakeHandlerVim: stdout: channel 35 open, 'error: aborting due to previous error^@^@'
[2016-12-29T11:15:13+0100 @39.840, debug] [10.35] stderr: cargo: ['error: aborting due to previous error', '', '']
[2016-12-29T11:15:13+0100 @39.869, debug] [10.35] MakeHandlerVim: stdout: channel 35 open, 'error: Could not compile `beersury-api`.^@^@To learn more, run the command again with --verbose.^@
[2016-12-29T11:15:13+0100 @39.869, debug] [10.35] stderr: cargo: ['error: Could not compile `beersury-api`.', '', 'To learn more, run the command again with --verbose.', '']
[2016-12-29T11:15:13+0100 @39.873, debug] [10.35] MakeHandlerVim: exit: channel 35 closed, job_info: {'status': 'dead', 'stoponexit': 'term', 'exitval': 101, 'exit_cb': 0, 'channel': channel
[2016-12-29T11:15:13+0100 @39.874, debug] [10.35] exit: cargo: 101
[2016-12-29T11:15:13+0100 @39.874, debug] Not processing output for mode c
[2016-12-29T11:15:13+0100 @39.875, debug] [10.35] cargo: completed with exit code 101.
[2016-12-29T11:15:13+0100 @39.876, debug] [10.35] Output left to be processed, not cleaning job yet.
[2016-12-29T11:15:13+0100 @40.052, debug] [11] Running makers: cargo ([{'ft': '', 'errorformat': '%-Gerror: aborting due to previous error,%-Gerror: aborting due to %\\d%\\+ previous errors,
[2016-12-29T11:15:13+0100 @40.053, verb ] [10.35] Found already running job for the same maker, restarting.
[2016-12-29T11:15:13+0100 @40.053, debug] Removing already finished job: 35
[2016-12-29T11:15:13+0100 @40.053, debug] All project-level errors cleaned.
[2016-12-29T11:15:13+0100 @40.054, debug] Removing signs {file: {}, project: {1: {51: 7000}}}
[2016-12-29T11:15:13+0100 @40.054, debug] Cleaning old signs in buffer 1:  {1: {51: 7000}}
[2016-12-29T11:15:13+0100 @40.055, debug] Unplacing sign: sign unplace 7000 buffer=1
[2016-12-29T11:15:13+0100 @40.062, debug] Skipping User autocmd NeomakeJobFinished: no hooks.
[2016-12-29T11:15:13+0100 @40.062, debug] Skipping User autocmd NeomakeFinished: no hooks.
```

**Comment by ChrisBuchholz** [comment] 2016-12-29 14:02
@blueyed: I'm not sure what you want me to do with git-bisect. It's not an error that happens only in this instance. It happens all the time after a few minutes of working on any rust project.

**Comment by blueyed** [comment] 2016-12-29 14:27
@ChrisBuchholz 
I've meant to bisect Neomake.

But it's fine, I think https://github.com/neomake/neomake/pull/903 will fix it.

It happens when output is not processed directly, because you're in command line mode, and then the job is cleaned when the maker is restarted ("Found already running job for the same maker, restarting.").
The restarting is buggy currently, but should be fixed in the "serialize" branch.

**Closed** 2016-12-29 14:30 UTC
Labels: bug

**Comment by ChrisBuchholz** [comment] 2016-12-29 15:32
@blueyed: sweet! When will the fix land in stable?

**Comment by blueyed** [comment] 2016-12-29 15:53
It is merged already.
