### ISSUE TITLE
:Neomake cargo makes zombie processes

### ISSUE THREAD

**Issue by Ploppz** [neomake/neomake#1529] opened 2017-08-28 13:40 UTC
nvim v0.2.0
`:Neomake cargo` makes no location list and has no visible effect. Then when I try to compile with `cargo build`, it's blocked: "Blocking waiting for file lock on build directory".
```
$ ps aux | grep cargo
ploppz    5581  0.0  0.4 226452 77456 pts/3    SNl+ 15:23   0:00 /home/ploppz/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/cargo check --message-format=json --quiet
ploppz    5855  0.0  0.2 109764 42052 pts/3    SN+  15:23   0:00 /home/ploppz/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/cargo check --message-format=json --quiet
ploppz    5867  0.0  0.2 109764 42328 pts/3    SN+  15:23   0:00 /home/ploppz/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/cargo check --message-format=json --quiet
ploppz    5871  0.0  0.1  39164 18412 pts/3    SN+  15:23   0:00 cargo check --message-format=json --quiet
ploppz    5872  0.0  0.2 109764 42712 pts/3    SN+  15:23   0:00 /home/ploppz/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/cargo check --message-format=json --quiet
```

I figured it's quite related to this ( https://github.com/neomake/neomake/issues/1216 ) but it's so long time ago, and I thought cargo check is only recent?

**Comment by blueyed** [comment] 2017-11-13 21:56
https://github.com/neomake/neomake/pull/1727 might help here.

**Comment by blueyed** [comment] 2017-11-13 21:58
Closing as duplicate of #1216 for now.

**Closed by blueyed** 2017-11-13 21:58 UTC
