### ISSUE TITLE
Error detected while processing function neomake#MakeHandler..<SNR>132_RegisterJobOutput..neomake#ProcessCurrentBuffer:

### ISSUE THREAD

**Issue by nathanielks** [neomake/neomake#322] opened 2016-03-01 06:00 UTC
Happy Monday, all!

I've got eslint working great so far, but whenever I run `:lopen` `:lclose` `:lopen`, it freaks out with the error message provided in the title. There's some extra bits included as well. Here's the whole output:

```
Error detected while processing function neomake#MakeHandler..<SNR>132_RegisterJobOutput..neomake#ProcessCurrentBuffer:
line    6:
E716: Key not present in Dictionary: 3
```

Let me know whatever else I can provide!

**Comment by nathanielks** [comment] 2016-03-01 06:07
It also causes the X's to disappear fwiw

**Comment by theamazingfedex** [comment] 2016-03-01 18:50
What version of NeoVim are you using? Try updating to the most recent version and see if that helps.

**Comment by nathanielks** [comment] 2016-03-01 18:52
Currently on 0.1.2 =\

**Comment by theamazingfedex** [comment] 2016-03-01 19:11
Try updating from the HEAD revision of [NeoVim](https://github.com/neovim/neovim/wiki/Installing-Neovim), just for funsies, and see if anything different happens. I'm on `0.1.3`, and not having that issue.

**Comment by nathanielks** [comment] 2016-03-01 19:46
Yarp, still exists, though slightly different this time:

```
Error detected while processing function neomake#MakeHandler[36]..<SNR>140_RegisterJobOutput[14]..neomake#ProcessCurrentBuffer:
line    6:                                                                                                                     
E716: Key not present in Dictionary: 3                                                                                         
```

**Comment by theamazingfedex** [comment] 2016-03-01 20:01
Can you go through your .vimrc and copy each line that deals with neomake, and paste it into here?

**Comment by nathanielks** [comment] 2016-03-01 20:03
Yarp!

```
let g:neomake_javascript_enabled_makers = ['eslint']
autocmd! BufWritePost,BufEnter * Neomake

nmap <Leader><Space>o :lopen<CR>      " open location window
nmap <Leader><Space>c :lclose<CR>     " close location window
nmap <Leader><Space>, :ll<CR>         " go to current error/warning
nmap <Leader><Space>n :lnext<CR>      " next error/warning
nmap <Leader><Space>p :lprev<CR>      " previous error/warning
```

**Comment by theamazingfedex** [comment] 2016-03-01 20:39
Next, add `let g:neomake_verbose=3`, reproduce this error, and copy the relevant output from `:messages` into here.

**Comment by nathanielks** [comment] 2016-03-02 01:13
The search continues! It looks like eslint is borked somewhere, but when I run eslint on the file outside of nvim, it works as expected. Here's the output of `:messages`

```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
"src/main.js" 35L, 1398C
Neomake: Starting: eslint -f compact /Users/aang/Code/GitHub/redux-starter/src/main.js
Neomake: eslint complete with exit code 0
Neomake: File-level errors cleaned in buffer 1
"src/main.js" 35L, 1399C written
Neomake: Starting: eslint -f compact /Users/aang/Code/GitHub/redux-starter/src/main.js
Neomake: eslint stdout: /Users/aang/Code/GitHub/redux-starter/src/main.js: line 6, col 34, Error - Extra semicolon. (semi)
Neomake: eslint stdout:
Neomake: eslint stdout: 1 problem
Neomake: eslint stdout:
Neomake: eslint stdout done.
Neomake: eslint processing 4 lines of output
Neomake: File-level errors cleaned in buffer 1
Neomake: Placing sign: sign place 5000 line=6 name=neomake_err buffer=1
Neomake: eslint complete with exit code 1
Neomake: WideMessage echo eslint: Extra semicolon. (semi)
Neomake: WideMessage echo eslint: Extra semicolon. (semi)
Neomake: Nothing to make: no enabled makers
Neomake: Starting: eslint -f compact /Users/aang/Code/GitHub/redux-starter/src/main.js
Neomake: WideMessage echo eslint: Extra semicolon. (semi)
Neomake: Nothing to make: no enabled makers
Neomake: eslint stdout: /Users/aang/Code/GitHub/redux-starter/src/main.js: line 6, col 34, Error - Extra semicolon. (semi)
Neomake: eslint stdout:
Neomake: eslint stdout: 1 problem
Neomake: eslint stdout:
Neomake: eslint stdout done.
Neomake: Cleaning old signs in buffer 1:  {1: {6: 5000}}
Neomake: Unplacing sign: sign unplace 5000 buffer=1
Neomake: eslint processing 4 lines of output
Neomake: File-level errors cleaned in buffer 1
Neomake: Placing sign: sign place 5000 line=6 name=neomake_err buffer=1
Neomake: Nothing to make: no enabled makers
Neomake: eslint complete with exit code 1
Neomake: next makers [eslint]
Neomake: Starting: eslint -f compact
Neomake: eslint stdout: test: no path given
Neomake: eslint stdout:
Neomake: eslint stdout:
Neomake: eslint stdout done.
Neomake: eslint processing 3 lines of output
Neomake: eslint processing 3 lines of output
Error detected while processing function neomake#MakeHandler[36]..<SNR>140_RegisterJobOutput[14]..neomake#ProcessCurrentBuffer:
line    6:
E716: Key not present in Dictionary: 3
Neomake: eslint stderr: /Users/aang/Code/GitHub/redux-starter/node_modules/eslint/node_modules/glob/sync.js:29
Neomake: eslint stderr:     throw new Error('must provide pattern')
Neomake: eslint stderr:     ^
Neomake: eslint stderr:
Neomake: eslint stderr: Error: must provide pattern
Neomake: eslint stderr:     at new GlobSync (/Users/aang/Code/GitHub/redux-starter/node_modules/eslint/node_modules/glob/sync.js:29:11)
Neomake: eslint stderr:     at Function.globSync [as sync] (/Users/aang/Code/GitHub/redux-starter/node_modules/eslint/node_modules/glob/sync.js:24:10)
Neomake: eslint stderr:     at /Users/aang/Code/GitHub/redux-starter/node_modules/eslint/lib/cli-engine.js:631:22
Neomake: eslint stderr:     at Array.forEach (native)
Neomake: eslint stderr:     at CLIEngine.executeOnFiles (/Users/aang/Code/GitHub/redux-starter/node_modules/eslint/lib/cli-engine.js:624:18)
Neomake: eslint stderr:     at Object.cli.execute (/Users/aang/Code/GitHub/redux-starter/node_modules/eslint/lib/cli.js:178:95)
Neomake: eslint stderr:     at Object.<anonymous> (/Users/aang/Code/GitHub/redux-starter/node_modules/eslint/bin/eslint.js:60:20)
Neomake: eslint stderr:     at Module._compile (module.js:413:34)
Neomake: eslint stderr:     at Object.Module._extensions..js (module.js:422:10)
Neomake: eslint stderr:     at Module.load (module.js:357:32)
Neomake: eslint stderr:
Neomake: eslint stderr done.
Neomake: eslint processing 18 lines of output
Neomake: eslint processing 18 lines of output
Error detected while processing function neomake#MakeHandler[36]..<SNR>140_RegisterJobOutput[14]..neomake#ProcessCurrentBuffer:
line    6:
E716: Key not present in Dictionary: 3
Neomake: eslint processing 18 lines of output
Neomake: eslint processing 18 lines of output
Error detected while processing function neomake#MakeHandler[42]..<SNR>140_RegisterJobOutput[14]..neomake#ProcessCurrentBuffer:
line    6:
E716: Key not present in Dictionary: 3
```

**Comment by nathanielks** [comment] 2016-03-02 01:17
Okie doke, I'm able to prevent this error by

1. `:lopen`
2. Move to the uppermost pane
3. `:lclose`
4. Rinse and Repeat

So for some reason the error window is still selected/in focus even after it's been closed and passes no filename for eslint to process?

**Comment by theamazingfedex** [comment] 2016-03-02 01:47
Seems like the file isn't getting passed to eslint one of the times it's getting called. Maybe try explicitly setting your neomake_javascript_eslint_maker

**Comment by nathanielks** [comment] 2016-03-02 19:33
Unfortunately that didn't change the behavior. I did realize something though: as long as I wait for eslint to finish linting, opening and closing won't produce that error output. It's only when I open and close while eslint is processing that the error gets thrown. I found this out by watching the status line and waiting till it produced an error message, hinting that it was done.

**Comment by jaux** [comment] 2016-06-04 06:30
I have similar issue with nvim v0.1.5 and standardjs, here is the `:messages` output:

```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
"~/Workspace/tmp/test1.js" 1L, 22C
Neomake: Starting: standard /Users/yeliu/Workspace/tmp/test1.js
Neomake: standard stderr: standard: Use JavaScript Standard Style (http://standardjs.com)
Neomake: standard stderr:
Neomake: standard stderr done.
Neomake: standard processing 2 lines of output
Neomake: standard stdout:   /Users/yeliu/Workspace/tmp/test1.js:1:21: Extra semicolon.
Neomake: standard stdout:
Neomake: standard stdout done.
Neomake: standard processing 2 lines of output
Neomake: File-level errors cleaned in buffer 1
Neomake: Placing sign: sign place 5000 line=1 name=neomake_err buffer=1
Neomake: standard completed with exit code 1
Neomake: WideMessage echo standard: Extra semicolon.
Neomake: next makers [standard]
Neomake: Starting: standard /Users/yeliu/Workspace/tmp/test1.js
Neomake: standard stderr: standard: Use JavaScript Standard Style (http://standardjs.com)
Neomake: standard stderr:
Neomake: standard stderr done.
Neomake: standard processing 2 lines of output
Neomake: standard stdout:   /Users/yeliu/Workspace/tmp/test1.js:1:21: Extra semicolon.
Neomake: standard stdout:
Neomake: standard stdout done.
Neomake: standard processing 2 lines of output
Neomake: File-level errors cleaned in buffer 1
Neomake: Cleaning old signs in buffer 1:  {1: {1: 5000}}
Neomake: Unplacing sign: sign unplace 5000 buffer=1
Neomake: Placing sign: sign place 5000 line=1 name=neomake_err buffer=1
Neomake: standard completed with exit code 1
Neomake: WideMessage echo standard: Extra semicolon.
"~/Workspace/tmp/test2.js" 1L, 22C
Neomake: Starting: standard /Users/yeliu/Workspace/tmp/test2.js
Neomake: standard stderr: standard: Use JavaScript Standard Style (http://standardjs.com)
Neomake: standard stderr:
Neomake: standard stderr done.
Neomake: standard processing 2 lines of output
Error detected while processing function neomake#MakeHandler[36]..<SNR>66_RegisterJobOutput[17]..neomake#ProcessCurrentWindow[5]..<SNR>66_ProcessJobOutput[12]..<SNR>66_AddExprCallb
ack:
line    5:
E716: Key not present in Dictionary: 2
Error detected while processing function neomake#MakeHandler[36]..<SNR>66_RegisterJobOutput[17]..neomake#ProcessCurrentWindow[5]..<SNR>66_ProcessJobOutput[12]..<SNR>66_AddExprCallb
ack:
line    5:
E15: Invalid expression: file_mode ? s:loclist_nr[a:maker.winnr] : s:qflist_nr
```

**Comment by jaux** [comment] 2016-06-04 06:58
I found my issue was caused by minibufexpl.vim plugin, neomake worked fine once I disabled it.

**Comment by nicodebo** [comment] 2016-07-12 22:41
hi,
I also have a similar issue with `NVIM 0.1.5-dev`. In fact my error message look almost the same as jaux but different numbers.

It is happening when opening a file with nvim from the command line. However, when opening the same file from Nerdtree (for example), there is no error message.

In my case, removing the [Nerdtree](https://github.com/scrooloose/nerdtree) plugin solved the issue. (And I'm not using the [minibufexpl.vim](https://github.com/fholgado/minibufexpl.vim)

**Comment by blueyed** [comment] 2016-07-13 00:07
@nicodebo 
Please post your error, when using current master.
The line numbers are important here.

**Comment by nicodebo** [comment] 2016-07-13 10:24
Here is the full message :
`Error detected while processing function neomake#MakeHandler[33]..<SNR>132_RegisterJobOutput[23]..neomake#ProcessCurrentWindow[5]..<SNR>132_ProcessJobOutput[13]..<SNR>132_AddExprCallback :                                          
line    6 :                                                                                                     
E716: Key not present in Dictionary: 2                                                                 
Error detected while processing function neomake#MakeHandler[33]..<SNR>132_RegisterJobOutput[23]..neomake#ProcessCurrentWindow[5]..<SNR>132_ProcessJobOutput[13]..<SNR>132_AddExprCallback :                                          
line    6 :                                                                                                     
E15: Invalid expression : file_mode ? s:loclist_nr[a:maker.winnr] : s:qflist_nr`

However I'm not sure about what you mean by "using the current master". I have installed and regularly updated nvim through the [ppa method](https://github.com/neovim/neovim/wiki/Installing-Neovim). Do you mean I shoud switch to [building neovim](https://github.com/neovim/neovim/wiki/Building-Neovim) ?

**Comment by blueyed** [comment] 2016-07-13 10:58
@nicodebo 
I've meant Neomake master - make sure to use the latest version.

**Comment by blueyed** [comment] 2016-10-02 15:45
I am going to close this, since I believe the original issue should have been fixed.

Please create a new issue in case there is still a problem.

**Closed by blueyed** 2016-10-02 15:45 UTC
Labels: bug
