### ISSUE TITLE
Neomake "IDE" (lint as you type)

### ISSUE THREAD

**Issue by dojoteef** [neomake/neomake#543] opened 2016-08-09 15:53 UTC
Hi! I'm really loving neomake's asynchronous mode. I liked it so much that I spent some time implementing an [IDE like feature](https://github.com/dojoteef/dotfiles/blob/ecafedff904df58222712ae06eb5a232c450781d/link/.vimrc#L463) in my vimrc which will lint code as you type. I'm not sure how extensible or flexible it is since I have to hack around a bit to make it work (though my approach doesn't change neomake in anyway). I'd love to hear some feedback and see if this is something that neomake could try to support natively so the ugly hacks would not be necessary (especially if changes in neomake break the code).

NOTE: I got inspiration for this from the following [blog post](https://www.gregjs.com/vim/2015/lint-as-you-type-with-neovim-and-neomake/). The approach in the blog post had a major caveat, it would write your file to disk every time you left insert mode so the neomake makers could run over the code. I wanted an approach that would work even while you were still insert mode and would not require saving you changes to the file you were editing. That's what my code supports.

**Comment by blueyed** [comment] 2016-08-09 19:58
Wow, very decent job! :cherries: 

I somehow like that you're using hidden API already (which was added for tests) with `neomake#has_async_support`.. :)

Since I cannot leave comments directly in the code/commit, I'll leave some here:

- s:neomake_windo (https://github.com/dojoteef/dotfiles/blob/ecafedff904df58222712ae06eb5a232c450781d/link/.vimrc#L662): check out https://github.com/vim-scripts/ArgsAndMore/blob/master/autoload/ArgsAndMore.vim#L127 (you can probably make it easier with `noautocmd`?!).
- you should use a prefix with `b:lastchangedtick`

Altogether, I've only skimmed it, but you certainly should move it into its own repo/plugin (especially given that it takes the most part of your vimrc currently).

Given all  the code I assume that it is pretty bad with regard to performance, isn't it?

**Comment by dojoteef** [comment] 2016-08-09 21:00
> Wow, very decent job! 🍒

Thanks! It's my first attempt at any real vimscript and I'm pretty happy with the end result.

> I somehow like that you're using hidden API already (which was added for tests) with `neomake#has_async_support`.. :)

Yeah I had to go digging through the neomake source code to figure out how best to implement the functionality needed for this feature.

> - s:neomake_windo (https://github.com/dojoteef/dotfiles/blob/ecafedff904df58222712ae06eb5a232c450781d/link/.vimrc#L662): check out https://github.com/vim-scripts/ArgsAndMore/blob/master/autoload/ArgsAndMore.vim#L127 (you can probably make it easier with noautocmd?!).

So I cannot simply use vim's `windo` since I need to break out of the loop early based on the return value of the function, which `windo` does not support (though from the documentation it looks like if I intentionally throw an error I could get close to the same functionality). Additionally I'm using eventignore rather than noautocmd so that I only ignore the autocmds that I specifically know I am triggering (by opening/closing the location lists).

> - you should use a prefix with b:lastchangedtick

Good catch!

> Altogether, I've only skimmed it, but you certainly should move it into its own repo/plugin (especially given that it takes the most part of your vimrc currently).

Yeah I initially created it in order to have something that works for me. It was much smaller scope, but as I started to make it more and more functional it grew in size 😲. The main reason I haven't created a repo/plugin for it is that I wanted to see if this is functionality that can be built into neomake (or at least have neomake expose better APIs to make this "IDE" into less of a hack). Right now there are quite a few hacky things. For example I have a hidden buffer backing a file in a temporary directory that neomake actually runs the maker on, then when the results come back I use the postprocess to change the buffer number (and potentially the error type if none is specified). It's not the most straightforward approach.

So my question still stands, is this something that makes sense to have support for in neomake (considering it already has asynchronous builds and lints, it seems like adding support for linting as you type would make sense as part of neomake). If not and I do end up making a separate plugin for it, would pull requests that refactor the code and/or expose APIs from neomake to reduce the hackiness of my approach be accepted?

> Given all the code I assume that it is pretty bad with regard to performance, isn't it?

Actually I haven't noticed a performance issue with my code running this on my 2013 Macbook Pro. Though I did see some performance degradation when combined with [vim-airline](https://github.com/vim-airline/vim-airline) which is why I had to do [this](https://github.com/dojoteef/dotfiles/blob/ecafedff904df58222712ae06eb5a232c450781d/link/.vimrc#L745). That said I've only run it on small shell files and go files so far. I haven't tested it on anything larger yet. I imagine that depending on the quickfix/location list management options chosen it could be very slow over a remote connection (due to opening/closing the location list a lot). That's part of the reason I put so much effort into coming up with multiple approaches for management of those windows.

**Comment by blueyed** [comment] 2016-08-10 12:33
> is this something that makes sense to have support for in neomake

Yes!

> would pull requests that refactor the code and/or expose APIs from neomake to reduce the hackiness of my approach be accepted

Always, of course.. :)
I think that makes sense in general, even when you are adding it to Neomake itself.

Please consider adding tests for this while you are integrating it.  Let me know, if you need help with that.  `make test` should work out of the box, and you can run only some file/module, e.g. `tests/neomake.vader`.

**Comment by purpleP** [comment] 2016-08-11 10:30
@dojoteef @blueyed  If you need any help creating pull request for this - let me know. Maybe I could help with something. I think now that I know basics of vimscript I could be useful.

**Comment by dojoteef** [comment] 2016-08-17 20:27
@coxley The only way to have the linter run over the contents of the buffer is to write it to disk. There is no other way. I thought it might be possible to use the swap file that vim creates to run the linters on, but it is not a viable solution as the swapfile is a binary file that has metadata in addition to the text of the buffer.

That said the approach I took is no different than vim writing out a swapfile every so often if you have the `swapfile` option turned on. Of course if writing the file to disk in any form is something you do not desire, then you can continue running neomake manually upon saving the file or by adding an autocmd like `autocmd! BufWritePost,BufEnter * Neomake` to your .vimrc to automatically run Neomake on save.

**Comment by coxley** [comment] 2016-08-19 05:12
Oh well, one can dream. :) Thanks for the closure

**Comment by Cypher1** [comment] 2016-08-20 08:06
How hard would it be to add all this functionality as a plugin so that we can build on it over time?

Cheers, great stuff.

**Comment by saaguero** [comment] 2016-08-30 23:21
Probably is what you're doing already, but I will suggest to try something similar than the approach taken by [vim-gutter](https://github.com/airblade/vim-gitgutter/blob/6ac50396002ad38668e3cf9d0c3760d03d95c0c9/autoload/gitgutter/diff.vim#L53)

**Comment by bounceme** [comment] 2016-08-31 02:34
make the linters run on tempfiles? unless that is what you have already, i haven't checked

**Comment by bounceme** [comment] 2016-08-31 11:16
your wild buffer changing method could probably fail with the `hidden` option. I happened to find this article, though it is irrelevant on windows: https://en.wikipedia.org/wiki/Process_substitution

I am more in favour of the piping method by @ivalkeen

**Comment by ivalkeen** [comment] 2016-09-22 19:48
> The only way to have the linter run over the contents of the buffer is to write it to disk. There is no other way.

@dojoteef I'm not so sure about that. Some linters (at least eslint for javascript and rubocop for ruby) support reading from stdin instead of reading from file. Which means that it should be possible to run them and pass the content of the unsaved buffer. I have a prototype of this approach (unfortunately don't have much time to finish it at the moment): https://github.com/neomake/neomake/pull/393

**Comment by purpleP** [comment] 2016-09-27 14:35
@blueyed Offtopic. You know what stops me most of a time from contributing to some repositories? Most projects (including this I think) lacks high-level description of what's inside them.
1. What problem are you trying to solve? This you have.
2. How do you solve it? General idea. Main components and their interactions. This you don't have AFAIK.
Because of that people that would love to contribute need to spend a lot of time reading code and reconstructing the big picture from little details.
Of course this would take original developers time etc, but if we want people to contribute it's worth it IMHO.
Just providing my opinion, in case you interested.

@ivalkeen If a linter can only read from file, why can't we pipe like this.

Some stupid script for testing, that can't read from stdin.

```
function some {
    value=$(<$1)
    echo $value
}

```
And here we are making it read from stdin
```
$echo blabla | some /dev/stdin
$blabla
```

Because I really would like this feature to be implemented I'd like to ask what's the problem?

I mean conceptually all neomake should do is to give a way to freeze some arguments for linters, pass data to them and then transform their output into appropriate representation in vim. This shouldn't be hard.
And all we want to add is that when the buffer is changed do the same exact thing, but instead of using file, use buffer. Temporary files, /dev/stdin, anything.
Can someone explain what is the problem here?

**Comment by blueyed** [comment] 2016-09-27 18:52
@purpleP 
Please feel free to step in and improve the documentation etc (there is #651 currently however).
I've only stepped in myself when this plugin was unmaintained.

My take on this idea is that I am not using it (I save a lot (basically when going out of insert mode)) and therefore am not interested that much in this feature myself.

I think the main problem is that you need to map the temporary file name to the real one again, and that the `$(<filename)` hack certainly does not work on Windows, does it?  (not that I would care, but just one of the issues).

You can also see from the lacking response to https://github.com/neomake/neomake/pull/517#issuecomment-238683881 and partly also https://github.com/neomake/neomake/pull/393#issuecomment-238683322 that there is not much standby to maintain this, after it has been merged.

Currently I'd say to get the Vim support in (#637), and once this (#393)  has tests it might be fine.

Have you tried #393 yourself already?  Feedback on PRs is also very useful and a nice way to contribute back.

**Comment by purpleP** [comment] 2016-09-28 11:56
@blueyed To improve docs I would need to understand what's going on in your repository. That's exactly the problem I'm talking about in the first place. I don't have time to read all the code and reconstruct the big picture. But I'm willing to contribute if it would be easy to understand what's going on.

All I'm saying is I think that probably there are a lot of people like me, who have enough time to write the code if someone give them the idea of what's going on, but not enough time to understand it from scratch. In my life I've dealt with legacy/others code many times. It's always takes a lot more time (in order of magnitude I think) to understand what's going on in the code if there's no one to ask about it. I've thought about it a lot and came to conclusion that the main issue is that there's no high level description of the code and interactions in it. The main questions are:
- High level idea. This program does that and that. To do that it uses such and such approach.
- Main modules are .... They interact in such and such way.

I'll give an example from my own [project](https://github.com/purpleP/flask_alchemy_rest/blob/master/Contributing.md). I've made it just now and it took no more than 5 minutes. I think it should help a lot to contributors to understand implementation, because now they now where to start, where to go next etc.

**Comment by bounceme** [comment] 2016-09-28 14:13
https://github.com/neomake/neomake/pull/393/files is ~20 lines of extra code and is simple enough to save a maintainer, who may not even use this feature, time

**Comment by purpleP** [comment] 2016-09-28 14:18
@bounceme If you're talking to me, then sorry, I can't understand what you've meant. Maybe you've meant?
>maintainer[s], who may not even use this feature, time
But I don't get the meaning of you post if even If I'm right.

**Comment by bounceme** [comment] 2016-09-28 14:28
The code proposed in this issue is much more complicated, and would be much harder to fixer a maintainer, if/when things break for users. piping is built exactly for purposes like these and it shows.

**Comment by dojoteef** [comment] 2016-09-28 17:44
@blueyed Sorry I have been absent a bit. It seems my suggestion has gotten quite the bit of feedback. Unfortunately getting this to a state where it can be merged into the current plugin with tests is not something I have time for. I might have time at the beginning of next year :-/

@bounceme @ivalkeen I appreciate the idea of piping the file, but it is limited in scope as many linters do not support reading from stdin. Using a pipe as the only way to accomplish linting the unwritten buffer seems to help only some workflows rather than something that would work for everyone.

Also note that running neomake over the temporary file is only a tiny part of what I wrote. The main focus is the "IDE" part. It automatically manages when to run neomake (don't have multiple running at the same time for the buffer as you type especially if linting takes a while), how and when to open the quickfix/location list (always open, open on errors), etc.

Unless specifically desired I am inclined to close this out and when/if I get time I will look at figuring out a way to merge this feature in. I just have one question: What portions (if any) of what I wrote make sense for the neomake project, i.e. should I pursue trying to get it merged in when I have time?

**Comment by blueyed** [comment] 2016-09-28 19:26
@purpleP 
> It's always takes a lot more time (in order of magnitude I think) to understand what's going on in the code if there's no one to ask about it.

There is no one really to ask: I also don't know some of the code myself (or features).
So I am quite in the same position as everybody else here (except for the creator, of course).
My approach was to add tests etc, to make sure there are no regressions etc.

>> Have you tried #393 yourself already?
> How could I try that except changing from neomake to fork in vim setup (bad idea)?

You must be kidding: you just have to add a new remote, fetch it, and check out the branch.
There are various ways to enhance this workflow, e.g. https://github.com/hub.
GitHub also provides refs for PRs, and I am using a `gcopr` (https://github.com/blueyed/oh-my-zsh/blob/6c78696097525bafe0d757baf8adb0f2da769639/plugins/git/git.plugin.zsh#L408-L429) function, i.e. `gcopr 393`.  This is really easy, especially when considering that you have a git checkout of the main repo already.

>> I think the main problem is that you need to map the temporary file name to the real one again
> How is that a problem? Store a Map

I've not said it's a hard problem, but just the main one, if you use it via `$(<tmpfilename)`.
And I just guessed there is a reason why some linters have a `--stdin` and `--filename` flag, which is used to use that name in the output, but anyway.

@dojoteef 
> Unless specifically desired I am inclined to close this out and when/if I get time I will look at figuring out a way to merge this feature in.

I'd leave it open, since it's still full of ideas and a good reference.

> I just have one question: What portions (if any) of what I wrote make sense for the neomake project, i.e. should I pursue trying to get it merged in when I have time?

Sorry, I would have to look at it in more detail.
I think I said it before when reviewing it, that there are portions that make sense to have in general.
Since then the core has changed a bit already (to the better I hope), so the "plugin" would be less intrusive.
I assume that youre approach would benefit from having #393 or something similar in?

**Comment by bounceme** [comment] 2016-09-28 20:00
My last thoughts i'll leave just in case someone feels like trying again.

This may be easier(simplified to basic concept):
bufenter- delete all existing linter temps and jobs, start lint process
lint finishes- parse and add to loclist, delete temp, start another job on next text change

this would make sure that only one job is running, and be a clear enough schedule without issues with differing lint speeds

**Comment by blueyed** [comment] 2016-09-28 20:03
@bounceme 
Thanks.

This sounds like we should behave like this by default, and there is currently some guard already to not have the same maker run twice.  It also likes it would benefit from providing some autocmd setup etc out of the box (https://github.com/neomake/neomake/projects/1).

**Comment by dojoteef** [comment] 2016-09-28 20:07
@blueyed Okay I'll keep it open.

The code I wrote works around the quirks of neomake, so probably a good third of the code could be removed if changes were made in neomake to better support the features I desired when writing this. I think having something similar to #393 would be useful to that end, but I feel like restricting it to only those linters that support taking input from stdin is very limiting. Though I have not surveyed all the linters, I would venture to say most linters do not support reading from stdin. For example it wouldn't work for common usecases that anyone writing shell scripts or vim plugins might use like [shellcheck](http://www.shellcheck.net) and [vint](https://github.com/Kuniwak/vint). In fact if using [programming language popularity](http://pypl.github.io/PYPL.html), Java is # 1 with nearly 25% of the share of search popularity, and neither of the two supported neomake linters `javac -xlint` nor [checkstyle](http://checkstyle.sourceforge.net) support reading from stdin.

That said I have nothing against having piping as an option, but if support is added for linters that don't support reading from stdin, then having the option to read from stdin seems like it would just be extra maintenance for no reason.

**Comment by bounceme** [comment] 2016-09-29 05:13
I think the only thing preventing the https://github.com/neomake/neomake/issues/543#issuecomment-250282420 approach is the lack of an ability to specify a filename for any of the predefined functions or commands. It should be easy even in a few vimrc lines after that

**Comment by bounceme** [comment] 2016-09-29 05:32
it would essentially look like this:
```
function! MYIDE()
  if exists('s:neomaketemp')
    call delete(s:neomaketemp)
    call neomake#CleanOldFileSignsAndErrors(buffer here) " i don't know what this does
    call setloclist(0,[])
  endif
  let s:neomaketemp = tempname() . expand('%:e')
  silent! call writefile(getline(1, '$'), s:neomaketemp)
  exe ':Neomake jshint ' . s:neomaketemp
endfunction
au bufenter *.js Neomake
au textchanged *.js call MYIDE()

```
Of course this is hard coding a ft and not killing processes but with effort(i made this in ~5 mins) it should work

**Comment by bounceme** [comment] 2016-09-29 06:45
cleaned up the last post several times

**Comment by bounceme** [comment] 2016-09-30 21:58
hey, people can test this version https://github.com/neomake/neomake/issues/663#issuecomment-250660647 by just pasting the code into their vimrc. id also be interested to hear any feedback

**Comment by dojoteef** [comment] 2016-11-04 23:22
@blueyed Just a heads up that I found some time to implement the lint as you type approach as a plugin. I present to you [neomake-autolint](https://github.com/dojoteef/neomake-autolint)!

I've removed all the extra location list/quickfix window management, so this is purely a lint as you type plugin, hence the name. I've also fixed some bugs with it.

If there is anything unclear just let me know. I hope some people find it useful. That said after writing the plugin it seems that there is a competing lint as you type plugin called [ALE (Asynchronous Lint Engine)](https://github.com/w0rp/ale) that seems to be picking up steam. It's only been on [Github](https://github.com) a couple of months and looks quite interesting. I've been considering giving it a shot when I have the chance.

And while this is a bit off topic, for those who use [YouCompleteMe](https://github.com/Valloric/YouCompleteMe) like I currently do, there is another contender that is equally new called [Complete](https://github.com/maralla/completor.vim).

Both of these new plugins are young and are powered by the fact that [Vim](https://github.com/vim/vim) now officially supports jobs. I guess people did not want to rely on [Neovim](https://github.com/neovim/neovim) to get there asynchronous plugins working.

**Comment by bounceme** [comment] 2016-11-05 02:08
Have you tried my version @dojoteef ? I know we have different approaches for this, but which is better or can be more flexible ( can handle project lintings etc. ) ?

**Comment by bounceme** [comment] 2016-11-05 04:13
people will just continue making linter frameworks which are likely never to reach a point of stability as neomake/syntastic. I think ale is pretty good, but so much work is being duplicated again to get this feature

**Comment by dojoteef** [comment] 2016-11-05 06:20
@bounceme The main difference we spoke about was whether [piping](https://github.com/neomake/neomake/issues/543#issuecomment-250182943) was the approach for sending the current buffer text to the linter or whether a temporary file should be used. If you are talking about your [gist](https://gist.github.com/bounceme/a2cb5c341af1b33c48689f64c678235f), I took a look and it appears to be at a very early stage of the approach I mentioned rather than something based on piping.

[neomake-autolint](https://github.com/dojoteef/neomake-autolint) works without any changes to neomake. It just uses the publicly exposed API to automatically create custom makers per buffer, which allows multiple files to be linted at the same time.

It is configurable. For example, it allows you to specify how long after you stop typing before trying to lint the file, so it does not just run on every text changed event. It includes the option to toggle automatic linting for a specific buffer on/off.

If any of the neomake contributors have time I would love to get their thoughts on my approach. I strongly believe it addresses any API concerns related to automatic linting, but I would love to get verification of that. It should be fairly straightforward to test given the [instructions](https://github.com/dojoteef/neomake-autolint#installation) on the plugin's page.

**Comment by bounceme** [comment] 2016-11-05 07:04
yes I was referring to my gist, which is mostly p.o.c . My version doesn't use any other buffers, it is a more 'transparent' implementation in my opinion. it does nothing to the current editor state, only starts the job on a tempfile in $TMPDIR and fixes the output so that it refers to the current buffer's path for the loclist to work. The end result seems to be equivalent though

**Comment by dojoteef** [comment] 2016-11-05 14:43
My plugin does not use any temporary buffers either. As I said it is a more stripped down version. Why don't you try it/look at it. While I had not closely looked at your gist before I made the plugin, the approach I landed on is more similar to yours than you think.

**Comment by purpleP** [comment] 2016-11-05 14:49
@dojoteef You're using temporary files, right? Isn't it worthless, because one can just save file on each change and have exactly the same result.

**Comment by bounceme** [comment] 2016-11-05 16:02
Haha. My mistake, I had some trouble understanding what changed from your vimrc version to the plugin version. your plugin is the best chance, probably, for code being incorporated into neomake

**Comment by dojoteef** [comment] 2016-11-05 16:43
@bounceme No worries. I'm not sure that my plugin needs to get folded into Neomake as it just uses public Neomake APIs and thus should be fine on it's own. No hackery or foolery, it just creates custom makers per buffer to accomplish the job.

**Comment by blueyed** [comment] 2016-11-06 00:30
Awesome!  Thanks!  :cherries: 
Will have to look at it, but I think we can close this issue here then for now.

**Closed by blueyed** 2016-11-06 00:30 UTC
Labels: enhancement, help wanted
