### ISSUE TITLE
Windows csslint and stylelint throwing error

### ISSUE THREAD

**Issue by zovt** [neomake/neomake#618] opened 2016-09-21 23:33 UTC
# Issue

Please adhere to this template for bug reports, but in case the issue is clear,
a feature requests, or if you know what you are doing you can do it
free-style, of course.  You should also remove this intro paragraph.

## Steps to reproduce

Please execute `:let g:neomake_verbose = 3` to enable verbose output, which
might help showing the issue already.  Please provide the output from
`:messages` afterwards (see below).

1. Open a CSS file
2. Save and run NeoMake

## Output of the ":NeomakeInfo" command
```
Async Support: 1
Current filetype: css
== Enabled makers ==
For the current filetype (with :Neomake): ['csslint', 'stylelint']
You can define g:neomake_css_enabled_makers to configure it (or b:neomake_css_enabled_makers).
For the project (with :Neomake!): []
You can define g:neomake_enabled_makers to configure it
```
## Versions

What is your Neovim or Vim version?  Please provide the relevant output from
`:version`.
```
NVIM v0.1.6-90-g0a0f72b
Build type: Release
Compilation: C:/msys64/mingw64/bin/gcc.exe -Wconversion -O2 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -D__USE_MINGW_ANSI_STDIO -D_WIN32_WINNT=0x0600 -Wvla -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -IC:/Projects/neovim-1kmqj/build/config -IC:/Projects/neovim-1kmqj/src -IC:/Projects/neovim-1kmqj/.deps/usr/include -IC:/Projects/neovim-1kmqj/.deps/usr/include -IC:/Projects/neovim-1kmqj/.deps/usr/include -IC:/msys64/mingw64/include -IC:/msys64/mingw64/include -IC:/Projects/neovim-1kmqj/build/src/nvim/auto -IC:/Projects/neovim-1kmqj/build/include
Compiled by appvyr-winppveyor@APPVYR-WIN

Optional features included (+) or not (-): -acl   +iconv    -jemalloc -tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"
```

## Output from ":messages"

You can use the command `:redir @+> | silent mess | redir END` to copy them to
your clipboard.

```
Error detected while processing function neomake#Make[13]..<SNR>34_Make[84]..<SNR>34_MakeJob:
line 56:
E903: Process for command "csslint" could not be spawned
Error detected while processing function neomake#Make[13]..<SNR>34_Make:
line 84:
E170: Missing :endfor
```

Some makers, like HTML tidy, run perfectly fine

**Comment by blueyed** [comment] 2016-09-21 23:55
What happens when you run `csslint` manually?

**Comment by zovt** [comment] 2016-09-22 00:00
Running in a shell works, running it with !csslint works

**Comment by blueyed** [comment] 2016-09-22 19:43
There should be some "Starting: " output in you `:messages`.
It says `Neomake: Starting: csslint --format=compact /home/user/src/neomake/t.css` for me.

The failing line is this: https://github.com/neomake/neomake/blob/85e8ae2e9506422c4eda6f7b4fb0e1c47e9bd887/autoload/neomake.vim#L131

So what does `:echo jobstart(['csslint', '--format=compact', '/path/to/css'])` give you?
And `echo system(['csslint', '--format=compact', '/path/to/css'])`?
If it also throws an error, then it appears to be a Neovim issue (related to Windows / your setup).

**Comment by zovt** [comment] 2016-09-22 20:31
`:echo jobstart(['csslint', '--format=compact', '/path/to/css'])`
```
E903: Process for command 'csslint' could not be spawned
-1
```

`echo system(['csslint', '--format=compact', '/path/to/css'])`
No visible output

**Comment by blueyed** [comment] 2016-09-22 21:39
@zovt looks like a Neovim issue then to me.
Please create it there.
Maybe there is something special about csslint, but I just could not reproduce it on Linux.

**Comment by blueyed** [comment] 2016-09-22 21:39
Closing the issue for Neomake.

**Comment by blueyed** [comment] 2016-09-22 21:40
(but please refer back to this issue for full reference, of course)

**Closed by blueyed** 2016-09-22 21:39 UTC
