### ISSUE TITLE
No linter output in neovim 0.2.2 appimage

### ISSUE THREAD

**Issue by cemsbr** [neomake/neomake#1816] opened 2018-01-12 01:32 UTC
_Updated: verbose NeomakeInfo without startify errors_

After saving a file or running ':Neomake', nothing happens in neovim. In vim, a window opens with linter results as expected

### Steps to reproduce
1. echo "Hello World" > neomake_test.py
2. nvim neomake_test.py
3. `:Neomake`

#### Neomake debug information
Async support: 1
Current filetype: python
Windows: 0
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]

##### Enabled makers
For the current filetype ("python", used with :Neomake):
 - python
   - append_file: 1
   - args: ['/home/cemsbr/.cache/vimfiles/repos/github.com/neomake/neomake/autoload/neomake/makers/ft/python/compile.py']
   - auto_enabled: 1
   - errorformat: '%E%f:%l:%c: %m'
   - exe: 'python'
   - output_stream: 'stdout'
   - serialize: 1
   - serialize_abort_on_error: 1
   - short_name: 'py'
 - frosted
   - append_file: 1
   - args: ['-vb']
   - auto_enabled: 1
   - errorformat: '%f:%l:%c:%m,%E%f:%l: %m,%-Z%p^,%-G%.%#'
   - exe: 'frosted'
   - WARNINGS:
     - maker's exe (frosted) is not executable.
 - flake8
   - append_file: 1
   - args: ['--format=default']
   - auto_enabled: 1
   - errorformat: '%E%f:%l: could not compile,%-Z%p^,%A%f:%l:%c: %t%n %m,%A%f:%l: %t%n %m,%-G%.%#'
   - exe: 'flake8'
   - postprocess: function('neomake#makers#ft#python#Flake8EntryProcess')
   - short_name: 'fl8'
   - supports_stdin: function('111')
 - pylint
   - append_file: 1
   - args: ['--output-format=text', '--msg-template="{path}:{line}:{column}:{C}: [{symbol}] {msg} [{msg_id}]"', '--reports=no']
   - auto_enabled: 1
   - errorformat: '%A%f:%l:%c:%t: %m,%A%f:%l: %m,%A%f:(%l): %m,%-Z%p^%.%#,%-G%.%#'
   - exe: 'pylint'
   - filter_output: function('112')
   - output_stream: 'stdout'
   - postprocess: [function('neomake#postprocess#GenericLengthPostprocess'), function('neomake#makers#ft#python#PylintEntryProcess')]
NOTE: you can define g:neomake_python_enabled_makers to configure it (or b:neomake_python_enabled_makers).

For the project (used with :Neomake!): None.
NOTE: you can define g:neomake_enabled_makers to configure it.

Default maker settings:
 - output_stream: 'both'
 - remove_invalid_entries: 0
 - buffer_output: 1

##### Settings
```
g:neomake_cursormoved_delay = 300
g:neomake_echo_current_error = 0
g:neomake_error_sign = {'texthl': 'error', 'text': '✖'}
g:neomake_info_sign = {'texthl': 'todo', 'text': 'ⓘ'}
g:neomake_java_javac_delete_output = 0
g:neomake_open_list = 2
g:neomake_place_signs = 1
g:neomake_verbose = 0
g:neomake_vim_enabled_makers = []
g:neomake_warning_sign = {'texthl': 'todo', 'text': '⚠'}


  makeprg=make
```

#### :version
```

NVIM v0.2.3-1-gd6f9d1df0
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/gcc-5 -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-a766c230-5e8b-4128-abe6-a12a167eebf5

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/home/travis/build/neovim/bot-ci/build/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
```

#### :messages
```
```

### Output from neovim's neomake_logfile
```
23:09:44 [D      ] [1.-:1:1] Exe (frosted) of auto-configured maker frosted is not executable, skipping.
23:09:44 [D      ] [1.-:1:1] Running makers: python (auto), flake8 (auto), pylint (auto).
23:09:44 [D      ] Defining sign: sign define neomake_file_err texthl=error text=✖.
23:09:44 [D      ] Defining sign: sign define neomake_project_err texthl=error text=✖.
23:09:44 [D      ] Defining sign: sign define neomake_file_warn texthl=todo text=⚠.
23:09:44 [D      ] Defining sign: sign define neomake_project_warn texthl=todo text=⚠.
23:09:44 [D      ] Defining sign: sign define neomake_file_info texthl=todo text=ⓘ.
23:09:44 [D      ] Defining sign: sign define neomake_project_info texthl=todo text=ⓘ.
23:09:44 [D      ] Defining sign: sign define neomake_file_msg texthl=NeomakeMessageSign text=➤.
23:09:44 [D      ] Defining sign: sign define neomake_project_msg texthl=NeomakeMessageSign text=➤.
23:09:44 [D      ] [-.-:1:1] Using setting serialize=1 from 'maker'.
23:09:44 [D      ] [-.-:1:1] Using setting append_file=1 from 'maker'.
23:09:44 [D      ] [1.1:1:1] Setting neomake_automake_tick.
23:09:44 [V      ] [1.1:1:1] Starting async job: ['python', '/home/cemsbr/.cache/vimfiles/repos/github.com/neomake/neomake/autoload/neomake/makers/ft/python/compile.py', '/tmp/neomake_test.py'].
23:09:44 [D      ] [1.1:1:1] cwd: /tmp.
23:09:44 [D +0.05] [1.1:1:1] exit: python: 1.
23:09:44 [D      ] [1.1:1:1] python: completed with exit code 1.
23:09:44 [D      ] [-.-:1:1] Using setting serialize_abort_on_error=1 from 'maker'.
23:09:44 [V      ] [1.-:-:1] Aborting next makers: flake8, pylint.
23:09:44 [D      ] [1.1:1:1] Cleaning jobinfo.
23:09:44 [D      ] [1.-:1:1] File-level errors cleaned.
23:09:44 [D      ] [1.-:-:1] Cleaning location list.
23:09:44 [D      ] [-.-:-:1] Handling location list: executing lclose.
23:09:44 [V      ] Calling User autocmd NeomakeFinished with context: {'options': {'bufnr': 1, 'ft': 'python', 'file_mode': 1, 'make_id': 1}, 'finished_jobs': [{'nvim_job': 4, 'cwd': '/tmp', 'file_mode': 1, 'as_string': function('94'), 'make_id': 1, 'id': 1, 'name': 'python', 'maker': {'_get_fname_for_args': function('56'), '_bind_args': function('97'), '_get_tempfilename': function('95'), 'short_name': 'py', 'name': 'python', 'auto_enabled': 1, 'serialize_abort_on_error': 1, 'exe': 'python', '_get_fname_for_buffer': function('96'), 'remove_invalid_entries': 0, 'serialize': 1, 'append_file': 1, 'buffer_output': 1, 'output_stream': 'stdout', '_get_argv': function('98'), 'errorformat': '%E%f:%l:%c: %m', 'args': ['/home/cemsbr/.cache/vimfiles/repos/github.com/neomake/neomake/autoload/neomake/makers/ft/python/compile.py']}, 'jobstart_opts': {'stdout_buffered': 1, 'on_exit': function('<SNR>251_nvim_exit_handler_buffered'), 'stderr_buffered': 1}, 'get_pid': function('93'), 'filename': '/tmp/neomake_test.py', 'bufnr': 1, 'serialize': 1, 'finished': 1, 'buffer_output': 1, 'output_stream': 'stdout', 'exit_code': 1, 'ft': 'python', 'argv': ['python', '/home/cemsbr/.cache/vimfiles/repos/github.com/neomake/neomake/autoload/neomake/makers/ft/python/compile.py', '/tmp/neomake_test.py']}], 'make_id': 1}.
23:09:44 [D      ] [1.-:1:1] Cleaning make info.
23:09:58 [D +13.4] Calling VimLeave.
```

### Output from vim's neomake_logfile (working)
```
23:08:56 [D      ] [1.-:1:1] Exe (frosted) of auto-configured maker frosted is not executable, skipping.
23:08:56 [D      ] [1.-:1:1] Running makers: python (auto), flake8 (auto), pylint (auto).
23:08:56 [D      ] Defining sign: sign define neomake_file_err texthl=error text=✖.
23:08:56 [D      ] Defining sign: sign define neomake_project_err texthl=error text=✖.
23:08:56 [D      ] Defining sign: sign define neomake_file_warn texthl=todo text=⚠.
23:08:56 [D      ] Defining sign: sign define neomake_project_warn texthl=todo text=⚠.
23:08:56 [D      ] Defining sign: sign define neomake_file_info texthl=todo text=ⓘ.
23:08:56 [D      ] Defining sign: sign define neomake_project_info texthl=todo text=ⓘ.
23:08:56 [D      ] Defining sign: sign define neomake_file_msg texthl=NeomakeMessageSign text=➤.
23:08:56 [D      ] Defining sign: sign define neomake_project_msg texthl=NeomakeMessageSign text=➤.
23:08:56 [D      ] [-.-:1:1] Using setting serialize=1 from 'maker'.
23:08:56 [D      ] [-.-:1:1] Using setting append_file=1 from 'maker'.
23:08:56 [D      ] [1.1:1:1] Setting neomake_automake_tick.
23:08:56 [V      ] [1.1:1:1] Starting async job: ['python', '/home/cemsbr/.cache/vimfiles/repos/github.com/neomake/neomake/autoload/neomake/makers/ft/python/compile.py', '/tmp/neomake_test.py'].
23:08:56 [D      ] [1.1:1:1] cwd: /tmp.
23:08:56 [D      ] [1.1:1:1] Vim job: {'status': 'run', 'stoponexit': 'term', 'tty_out': '', 'exitval': 0, 'exit_cb': 0, 'tty_in': '', 'channel': 'channel 1 open', 'process': 3443}.
23:08:56 [D      ] [1.1:1:1] Vim channel: {'status': 'open', 'id': 1, 'in_io': 'pipe', 'err_mode': 'RAW', 'in_status': 'open', 'out_io': 'pipe', 'err_io': 'pipe', 'err_status': 'open', 'out_timeout': 2000, 'out_status': 'open', 'out_mode': 'RAW', 'in_mode': 'RAW', 'in_timeout': 2000, 'err_timeout': 2000}.
23:08:56 [D +0.04] [1.1:1:1] stdout: python: ['/tmp/neomake_test.py:1:11: invalid syntax', ''].
23:08:56 [D      ] [1.1:1:1] exit: python: 1.
23:08:56 [D      ] [1.1:1:1] python: processing 1 lines of output.
23:08:56 [D      ] [1.1:1:1] Creating location list.
23:08:56 [D      ] [1.1:1:1] Processing 1 entries.
23:08:56 [D      ] [1.-:1:1] File-level errors cleaned.
23:08:56 [D      ] [-.-:1:1] Placing sign: sign place 5000 line=1 name=neomake_file_err buffer=1.
23:08:56 [D      ] [1.1:1:1] Handling location list: executing lwindow.
23:08:56 [D +0.03] [1.1:1:1] python: completed with exit code 1.
23:08:56 [D      ] [-.-:1:1] Using setting serialize_abort_on_error=1 from 'maker'.
23:08:56 [V      ] [1.-:-:1] Aborting next makers: flake8, pylint.
23:08:56 [D      ] [1.1:1:1] Cleaning jobinfo.
23:08:56 [D      ] WideMessage: echo python: invalid syntax (E).
23:08:56 [V      ] Calling User autocmd NeomakeFinished with context: {'options': {'bufnr': 1, 'ft': 'python', 'file_mode': 1, 'make_id': 1}, 'finished_jobs': [{'cwd': '/tmp', 'file_mode': 1, 'as_string': function('101'), 'make_id': 1, 'id': 1, 'name': 'python', 'maker': {'_get_fname_for_args': function('65'), '_bind_args': function('104'), '_get_tempfilename': function('102'), 'short_name': 'py', 'name': 'python', 'auto_enabled': 1, 'serialize_abort_on_error': 1, 'exe': 'python', '_get_fname_for_buffer': function('103'), 'remove_invalid_entries': 0, 'serialize': 1, 'append_file': 1, 'buffer_output': 1, 'output_stream': 'stdout', '_get_argv': function('105'), 'errorformat': '%E%f:%l:%c: %m', 'args': ['/home/cemsbr/.cache/vimfiles/repos/github.com/neomake/neomake/autoload/neomake/makers/ft/python/compile.py']}, 'get_pid': function('100'), 'filename': '/tmp/neomake_test.py', 'bufnr': 1, 'serialize': 1, 'vim_job': 'process 3443 dead', 'filter_output': '', 'buffer_output': 1, 'output_stream': 'stdout', 'exit_code': 1, 'ft': 'python', 'argv': ['python', '/home/cemsbr/.cache/vimfiles/repos/github.com/neomake/neomake/autoload/neomake/makers/ft/python/compile.py', '/tmp/neomake_test.py'], 'finished': 1}], 'make_id': 1}.
23:08:56 [D      ] [1.-:1:1] Cleaning make info.
```

**Comment by mhinz** [comment] 2018-01-12 11:04
Hi, Startify author here.

Since the Startify buffer usually gets wiped after you have seen it on Vim startup, but `:Neomake` clearly looking for it (`not found in 'runtimepath': "autoload/neomake/makers/ft/startify.vim"`), I guess `:Startify` is executed somewhere in the process. 

Sadly I can't reproduce it with Neovim, your Neomake options, and the given steps.

<details>
<summary>:NeomakeInfo in Startify buffer</summary>
##### Enabled makers
For the current filetype ("startify", used with :Neomake): None.
NOTE: you can define g:neomake_startify_enabled_makers to configure it (or b:neomake_startify_enabled_makers).

For the project (used with :Neomake!): None.
NOTE: you can define g:neomake_enabled_makers to configure it.

Default maker settings:
 - output_stream: 'both'
 - remove_invalid_entries: 0
 - buffer_output: 1

##### Settings
```
g:neomake_cursormoved_delay = 300
g:neomake_echo_current_error = 0
g:neomake_error_sign = {'texthl': 'error', 'text': '✖'}
g:neomake_info_sign = {'texthl': 'todo', 'text': 'ⓘ'}
g:neomake_java_javac_delete_output = 0
g:neomake_open_list = 2
g:neomake_place_signs = 1
g:neomake_verbose = 0
g:neomake_vim_enabled_makers = []
g:neomake_warning_sign = {'texthl': 'todo', 'text': '⚠'}

  makeprg=make
```
</details>

<details>
<summary>:NeomakeInfo in Python buffer</summary>
##### Enabled makers
For the current filetype ("python", used with :Neomake):
 - python
   - append_file: 1
   - args: ['/Users/mhi/.vim/bundle/neomake/autoload/neomake/makers/ft/python/compile.py']
   - auto_enabled: 1
   - errorformat: '%E%f:%l:%c: %m'
   - exe: 'python'
   - output_stream: 'stdout'
   - serialize: 1
   - serialize_abort_on_error: 1
   - short_name: 'py'
 - frosted
   - append_file: 1
   - args: ['-vb']
   - auto_enabled: 1
   - errorformat: '%f:%l:%c:%m,%E%f:%l: %m,%-Z%p^,%-G%.%#'
   - exe: 'frosted'
   - WARNINGS:
     - maker's exe (frosted) is not executable.
 - pyflakes
   - append_file: 1
   - args: []
   - auto_enabled: 1
   - errorformat: '%E%f:%l: could not compile,%-Z%p^,%E%f:%l:%c: %m,%E%f:%l: %m,%-G%.%#'
   - exe: 'pyflakes'
   - WARNINGS:
     - maker's exe (pyflakes) is not executable.
 - pycodestyle
   - append_file: 1
   - args: []
   - auto_enabled: 1
   - errorformat: '%f:%l:%c: %m'
   - exe: 'pep8'
   - postprocess: function('neomake#makers#ft#python#Pep8EntryProcess')
   - WARNINGS:
     - maker's exe (pep8) is not executable.
 - pydocstyle
   - append_file: 1
   - args: []
   - auto_enabled: 1
   - errorformat: '%W%f:%l %.%#:,%+C        %m'
   - exe: 'pep257'
   - postprocess: function('neomake#utils#CompressWhitespace')
   - WARNINGS:
     - maker's exe (pep257) is not executable.
 - pylint
   - append_file: 1
   - args: ['--output-format=text', '--msg-template="{path}:{line}:{column}:{C}: [{symbol}] {msg} [{msg_id}]"', '--reports=no']
   - auto_enabled: 1
   - errorformat: '%A%f:%l:%c:%t: %m,%A%f:%l: %m,%A%f:(%l): %m,%-Z%p^%.%#,%-G%.%#'
   - exe: 'pylint'
   - filter_output: function('13')
   - output_stream: 'stdout'
   - postprocess: [function('neomake#postprocess#GenericLengthPostprocess'), function('neomake#makers#ft#python#PylintEntryProcess')]
   - WARNINGS:
     - maker's exe (pylint) is not executable.
NOTE: you can define g:neomake_python_enabled_makers to configure it (or b:neomake_python_enabled_makers).

For the project (used with :Neomake!): None.
NOTE: you can define g:neomake_enabled_makers to configure it.

Default maker settings:
 - output_stream: 'both'
 - remove_invalid_entries: 0
 - buffer_output: 1

##### Settings
```
g:neomake_cursormoved_delay = 300
g:neomake_echo_current_error = 0
g:neomake_error_sign = {'texthl': 'error', 'text': '✖'}
g:neomake_info_sign = {'texthl': 'todo', 'text': 'ⓘ'}
g:neomake_java_javac_delete_output = 0
g:neomake_open_list = 2
g:neomake_place_signs = 1
g:neomake_verbose = 0
g:neomake_vim_enabled_makers = []
g:neomake_warning_sign = {'texthl': 'todo', 'text': '⚠'}

  makeprg=./%
        Last set from ~/.vim/init.vim
```
</details>

Just to be sure.. can you give your Startify options as well?

**Comment by cemsbr** [comment] 2018-01-12 14:51
Hi, mhinz. I couldn't reproduce it either. Probably it was solved after many updates I did while trying to solve this problem.

**Comment by cemsbr** [comment] 2018-01-12 14:54
Note: I tried the nightly neovim.appimage and it's working. It could be a neovim's bug, but I'm not sure.

**Comment by blueyed** [comment] 2018-01-13 14:11
It tries to use Neovim's runreleased buffered mode, but you were using just the Git version after 0.2.2 (d6f9d1d), where it was not included yet.

Since it works with the latest nightly, all is expected.

**Comment by blueyed** [comment] 2018-01-13 14:12
It checks for `has('nvim-0.2.3')` - is there a better way maybe?
(anyway likely not worth changing or looking it up)

**Comment by cemsbr** [comment] 2018-01-13 15:23
@blueyed, the version info in neovim is broken: `--version` of nvim.appimage 0.2.2 tells "NVIM v0.2.3-1-gd6f9d1df0" and, for 0.2.3, it's "NVIM v0.2.3-409-ga8ad6b4d5". As you can see, both are `v0.2.3` so the version detection is not working for latest stable Neovim.

**Comment by blueyed** [comment] 2018-01-14 17:52
@cemsbr 
Oh, so you are using 0.2.2?
Can you file an issue with Neovim then, please?

**Comment by blueyed** [comment] 2018-01-14 17:54
@cemsbr 
How did you install it?

**Comment by blueyed** [comment] 2018-01-14 17:55
/cc @justinmk
See the last comment from @cemsbr.

**Comment by blueyed** [comment] 2018-01-14 17:56
Found it: https://github.com/neovim/neovim/issues/7645.

**Comment by blueyed** [comment] 2018-01-14 18:39
Re-opening for now.
As a workaround you can use `:call neomake#config#set('maker_defaults.buffer_output', 0)`. (with current master)

**Comment by blueyed** [comment] 2018-01-14 23:54
Added a workaround/fix for this.

**Closed** 2018-01-14 23:54 UTC
Labels: bug
