### ISSUE TITLE
neomake and vim sessions

### ISSUE THREAD

**Issue by nicodebo** [neomake/neomake#864] opened 2016-12-17 14:18 UTC
### Issue

Since the recent commits, neomake throw me the following error when opening a vim session:

```"stat" 74L, 2364C
Error detected while processing function neomake#Make[9]..<SNR>109_Make:
line   44:
E121: Undefined variable: g:neomake_place_signs
E15: Invalid expression: g:neomake_place_signs
```

However, if i use revert neomake to the following commit https://github.com/neomake/neomake/commit/03047e730db205ff5146cc401fa03f778ccb84f0, the error does not show.

#### nvim version
NVIM 0.2.0-dev

#### neomake vimrc related lines
autocmd! BufWritePost,BufEnter * Neomake
let g:neomake_sh_enabled_makers = ['shellcheck']
let g:neomake_tex_enabled_makers = ['lacheck']

### Steps to reproduce

1) Download the following python file : https://github.com/nicodebo/dream-note/blob/master/lib/dreamnote/stat

2) Open the hereabove file and save a session:
```
nvim stat
:mksession /path/to/session/dir/session
```
3) Open the session
```
nvim -S /path/to/session/dir/session
```

### Output of the ":verb NeomakeInfo" command
```
#### Neomake debug information
Async support: 1
Current filetype: python


##### Enabled makers
For the current filetype (with :Neomake):
 - python
   errorformat: '%E%f:%l:%c: %m'
   args: ['-c', 'from __future__ import print_function
from sys import argv, exit
if len(argv) != 2:
    exit(64)
try:
    compile(open(argv[1]).read(), argv[1], ''exec'', 0, 1)
except SyntaxError as err:
    print(''%s:%s:%s: %s'' % (err.filename, err.lineno, err.offset, err.msg))
    exit(1)']
   exe: 'python'
 - pyflakes
   errorformat: '%E%f:%l: could not compile,%-Z%p^,%E%f:%l:%c: %m,%E%f:%l: %m,%-G%.%#'
   exe: 'pyflakes'
   args: []
 - pep8
       Error detected while processing function neomake#DisplayInfo[8]..<SNR>109_display_maker_info:
line    9:
E704: Funcref variable name must start with a capital: v
```

**Comment by blueyed** [comment] 2016-12-17 14:23
So c1ba734 is the first bad commit for you?

**Comment by nicodebo** [comment] 2016-12-17 14:30
yes, it is.

**Comment by blueyed** [comment] 2016-12-17 14:46
The problem is that the `BufEnter` gets executed before the `VimEnter`, but only for Neovim, not Vim.

Thanks for the report, I'll think about how to address this, and will fix it shortly.

FWIW: https://github.com/neomake/neomake/pull/865 fixes the error in `:NeomakeInfo`.

**Comment by blueyed** [comment] 2016-12-17 15:04
Should be fixed now.

**Closed** 2016-12-17 15:04 UTC

**Comment by nicodebo** [comment] 2016-12-17 15:32
Indeed, the error has disappeared.
Thank you
